// Auto-generated file. Do not edit.

class CfgVehicles {
class O_Truck_02_fuel_F;
class Truck_02_aa_base_lxWS;
class B_Truck_01_fuel_F;
class B_Truck_01_transport_F;
class B_Soldier_lite_F;
class I_pilot_F;
class B_Soldier_base_F;
class B_CTRG_Soldier_tna_F;
class O_Truck_02_covered_F;
class B_Heli_Transport_03_F;
class B_soldier_AR_F;
class I_G_Offroad_01_armed_F;
class I_G_HMG_02_high_F;
class O_Soldier_TL_F;
class Heli_Transport_02_base_F;
class Truck_02_Ammo_base_lxWS;
class B_Heli_Transport_01_F;
class B_static_AT_F;
class B_soldier_AAR_F;
class B_Truck_01_ammo_F;
class B_Quadbike_01_F;
class B_recon_F;
class B_MRAP_01_F;
class O_officer_F;
class B_CTRG_Soldier_Medic_tna_F;
class B_MBT_01_TUSK_F;
class B_MBT_01_arty_F;
class O_APC_Tracked_02_AA_F;
class O_APC_Tracked_02_cannon_F;
class B_soldier_UAV_F;
class B_Truck_01_box_F;
class B_Truck_01_Repair_F;
class B_CTRG_Soldier_Exp_tna_F;
class B_MRAP_01_hmg_F;
class B_recon_LAT_F;
class Truck_02_flatbed_base_lxWS;
class I_G_Offroad_01_F;
class B_Survivor_F;
class I_Soldier_AT_F;
class I_crew_F;
class B_Truck_01_cargo_F;
class O_V_Soldier_M_hex_F;
class I_Soldier_AAT_F;
class B_MRAP_01_gmg_F;
class I_G_Offroad_01_AT_F;
class Truck_02_box_base_lxWS;
class B_support_Mort_F;
class I_G_HMG_02_F;
class I_soldier_UAV_F;
class B_support_MG_F;
class B_recon_TL_F;
class O_Soldier_LAT_F;
class B_soldier_AT_F;
class O_V_Soldier_hex_F;
class B_CTRG_Soldier_AR_tna_F;
class Truck_02_cargo_base_lxWS;
class B_Heli_Transport_03_unarmed_F;
class B_Soldier_SL_F;
class B_static_AA_F;
class I_C_Soldier_Bandit_1_F;
class B_soldier_exp_F;
class C_Man_UAV_06_F;
class B_Truck_01_medical_F;
class B_support_AMort_F;
class B_Mortar_01_F;
class I_Soldier_AR_F;
class B_Soldier_GL_F;
class O_Truck_02_transport_F;
class B_Helipilot_F;
class Helicopter_Base_F;
class O_Heli_Light_02_unarmed_F;
class I_officer_F;
class B_Heli_Light_01_dynamicLoadout_F;
class B_MBT_01_mlrs_F;
class B_officer_F;
class B_Truck_01_covered_F;
class APC_Wheeled_02_base_v2_F;
class I_Mortar_01_F;
class B_support_GMG_F;
class B_APC_Tracked_01_CRV_F;
class I_C_Soldier_Bandit_4_F;
class B_recon_exp_F;
class B_recon_M_F;
class I_Soldier_TL_F;
class B_APC_Tracked_01_AA_F;
class B_CTRG_Soldier_LAT2_tna_F;
class I_G_Soldier_F;
class B_recon_JTAC_F;
class O_V_Soldier_LAT_hex_F;
class B_recon_medic_F;
class B_Truck_01_flatbed_F;
class B_T_VTOL_01_vehicle_F;
class B_G_Soldier_F;
class B_T_Pilot_F;
class I_G_Sharpshooter_F;
class O_Soldier_AR_F;
class B_Soldier_F;
class O_Heli_Attack_02_dynamicLoadout_F;
class C_Pickup_covered_rf;
class B_Soldier_unarmed_F;
class B_soldier_repair_F;
class B_Soldier_universal_F;
class B_UAV_AI_F;
class APC_Wheeled_01_base_F;
class B_soldier_AAA_F;
class UAV_01_base_F;
class B_crew_F;
class B_CTRG_Soldier_JTAC_tna_F;
class B_soldier_AA_F;
class B_UGV_01_rcws_F;
class I_MBT_03_cannon_F;
class B_soldier_LAT_F;
class C_Man_casual_1_F_afro;
class O_medic_F;
class I_C_Soldier_Bandit_5_F;
class I_C_Soldier_Para_2_F;
class B_Soldier_A_F;
class B_CTRG_soldier_GL_LAT_F;
class Pickup_01_hmg_base_rf;
class B_Fighter_Pilot_F;
class I_Soldier_GL_F;
class O_V_Soldier_TL_hex_F;
class B_soldier_mine_F;
class I_G_Soldier_exp_F;
class B_soldier_M_F;
class B_engineer_F;
class I_C_Soldier_Bandit_2_F;
class B_medic_F;
class I_Soldier_repair_F;
class zu23_base_lxWS;
class O_Soldier_GL_F;
class O_MBT_02_cannon_F;
class B_CTRG_Soldier_M_tna_F;
class B_MBT_01_cannon_F;
class B_Truck_01_mover_F;
class O_Soldier_F;
class B_Plane_CAS_01_dynamicLoadout_F;
class B_Heli_Attack_01_dynamicLoadout_F;
class B_Heli_Light_01_F;
class B_APC_Tracked_01_rcws_F;
class B_T_VTOL_01_infantry_F;
class I_soldier_F;
class O_soldier_UAV_F;
class O_V_Soldier_Medic_hex_F;
class B_soldier_LAT2_F;
class I_Truck_02_MRL_F;
class O_G_Soldier_F;
class B_soldier_AAT_F;
class B_Soldier_TL_F;
class B_T_VTOL_01_armed_F;
class B_soldier_PG_F;
class B_UGV_01_F;
class I_Soldier_AA_F;
class O_Heli_Light_02_dynamicLoadout_F;
class B_APC_Wheeled_01_cannon_F;
class B_support_AMG_F;
class C_Van_02_vehicle_F;
class O_crew_F;
class B_CTRG_Soldier_TL_tna_F;
class I_G_medic_F;
class B_Competitor_F;
class C_journalist_F;
class I_Soldier_AAA_F;

class B_UNA_Camo1_UniformHolder_lxWS: B_officer_F { scope = 1; scopeCurator = 1; };
class B_UNA_Camo2_UniformHolder_lxWS: B_crew_F { scope = 1; scopeCurator = 1; };
class B_UNA_Camo3_UniformHolder_lxWS: B_Soldier_F { scope = 1; scopeCurator = 1; };
class B_ION_Casual3_Uniform_lxWS: B_Competitor_F { scope = 1; scopeCurator = 1; };
class B_soldier_UAV_lxWS: B_soldier_UAV_F { scope = 1; scopeCurator = 1; };
class B_D_Soldier_universal_lxWS: B_Soldier_universal_F { scope = 1; scopeCurator = 1; };
class B_APC_Wheeled_01_cannon_lxWS: APC_Wheeled_01_base_F { scope = 1; scopeCurator = 1; };
class APC_Wheeled_01_atgm_base_lxWS: APC_Wheeled_01_base_F { scope = 1; scopeCurator = 1; };
class APC_Wheeled_01_command_base_lxWS: APC_Wheeled_01_base_F { scope = 1; scopeCurator = 1; };
class APC_Wheeled_01_mortar_base_lxWS: APC_Wheeled_01_base_F { scope = 1; scopeCurator = 1; };
class B_APC_Wheeled_01_atgm_lxWS: APC_Wheeled_01_atgm_base_lxWS { scope = 1; scopeCurator = 1; };
class B_APC_Wheeled_01_command_lxWS: APC_Wheeled_01_command_base_lxWS { scope = 1; scopeCurator = 1; };
class B_APC_Wheeled_01_mortar_lxWS: APC_Wheeled_01_mortar_base_lxWS { scope = 1; scopeCurator = 1; };
class B_ALC_Soldier_universal_lxWS: B_D_Soldier_universal_lxWS { scope = 1; scopeCurator = 1; };
class B_CTRG_soldier_1_noflag_lxws: B_Soldier_base_F { scope = 1; scopeCurator = 1; };
class B_CTRG_soldier_3_noflag_lxws: B_CTRG_soldier_1_noflag_lxws { scope = 1; scopeCurator = 1; };
class B_InvisibleUniform_lxws: B_Soldier_base_F { scope = 1; scopeCurator = 1; };
class I_InvisibleUniform_lxws: B_InvisibleUniform_lxws { scope = 1; scopeCurator = 1; };
class O_InvisibleUniform_lxws: B_InvisibleUniform_lxws { scope = 1; scopeCurator = 1; };
class C_InvisibleUniform_lxws: B_InvisibleUniform_lxws { scope = 1; scopeCurator = 1; };
class O_soldier_UAV_lxWS: O_soldier_UAV_F { scope = 1; scopeCurator = 1; };
class O_APC_Tracked_02_30mm_lxWS: O_APC_Tracked_02_cannon_F { scope = 1; scopeCurator = 1; };
class O_Truck_02_cargo_lxWS: Truck_02_cargo_base_lxWS { scope = 1; scopeCurator = 1; };
class O_Truck_02_flatbed_lxWS: Truck_02_flatbed_base_lxWS { scope = 1; scopeCurator = 1; };
class I_soldier_UAV_lxWS: I_soldier_UAV_F { scope = 1; scopeCurator = 1; };
class I_Truck_02_cargo_lxWS: Truck_02_cargo_base_lxWS { scope = 1; scopeCurator = 1; };
class I_Truck_02_flatbed_lxWS: Truck_02_flatbed_base_lxWS { scope = 1; scopeCurator = 1; };
class I_A_Truck_02_aa_lxWS: Truck_02_aa_base_lxWS { scope = 1; scopeCurator = 1; };
class Offroad_01_base_lxWS: I_G_Offroad_01_F { scope = 1; scopeCurator = 1; };
class Offroad_01_AT_lxWS: I_G_Offroad_01_AT_F { scope = 1; scopeCurator = 1; };
class Offroad_01_armed_lxWS: I_G_Offroad_01_armed_F { scope = 1; scopeCurator = 1; };
class Offroad_01_armor_base_lxWS: Offroad_01_base_lxWS { scope = 1; scopeCurator = 1; };
class Offroad_01_armor_AT_lxWS: Offroad_01_AT_lxWS { scope = 1; scopeCurator = 1; };
class Offroad_01_armor_armed_lxWS: Offroad_01_armed_lxWS { scope = 1; scopeCurator = 1; };
class Offroad_01_aa_lxWS: Offroad_01_armed_lxWS { scope = 1; scopeCurator = 1; };
class Offroad_01_armor_aa_lxWS: Offroad_01_aa_lxWS { scope = 1; scopeCurator = 1; };
class I_G_Offroad_01_armor_base_lxWS: Offroad_01_armor_base_lxWS { scope = 1; scopeCurator = 1; };
class I_G_Offroad_01_armor_AT_lxWS: Offroad_01_armor_AT_lxWS { scope = 1; scopeCurator = 1; };
class I_G_Offroad_01_armor_armed_lxWS: Offroad_01_armor_armed_lxWS { scope = 1; scopeCurator = 1; };
class I_G_Offroad_AA_lxWS: Offroad_01_aa_lxWS { scope = 1; scopeCurator = 1; };
class I_G_Soldier_UAV_lxWS: I_G_Soldier_F { scope = 1; scopeCurator = 1; };
class UAV_02_Base_lxWS: Helicopter_Base_F { scope = 1; scopeCurator = 1; };
class CIV_UAV_01_lxWS: UAV_01_base_F { scope = 1; scopeCurator = 1; };
class UAV_02_IED_Base_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class C_Journalist_lxWS: C_journalist_F { scope = 1; scopeCurator = 1; };
class C_Man_UAV_01_lxWS: C_Man_UAV_06_F { scope = 1; scopeCurator = 1; };
class C_Offroad_lxWS: Offroad_01_base_lxWS { scope = 1; scopeCurator = 1; };
class C_Truck_02_racing_lxWS: Truck_02_box_base_lxWS { scope = 1; scopeCurator = 1; };
class C_Truck_02_cargo_lxWS: Truck_02_cargo_base_lxWS { scope = 1; scopeCurator = 1; };
class C_Truck_02_flatbed_lxWS: Truck_02_flatbed_base_lxWS { scope = 1; scopeCurator = 1; };
class C_Argana_Pickup_police_lxWS: C_Pickup_covered_rf { scope = 1; scopeCurator = 1; };
class C_Argana_Van_02_vehicle_lxWS: C_Van_02_vehicle_F { scope = 1; scopeCurator = 1; };
class B_G_UAV_02_IED_lxWS: UAV_02_IED_Base_lxWS { scope = 1; scopeCurator = 1; };
class B_G_Offroad_01_armor_base_lxWS: I_G_Offroad_01_armor_base_lxWS { scope = 1; scopeCurator = 1; };
class B_G_Offroad_01_armor_AT_lxWS: I_G_Offroad_01_armor_AT_lxWS { scope = 1; scopeCurator = 1; };
class B_G_Offroad_01_armor_armed_lxWS: I_G_Offroad_01_armor_armed_lxWS { scope = 1; scopeCurator = 1; };
class B_G_Offroad_AA_lxWS: I_G_Offroad_AA_lxWS { scope = 1; scopeCurator = 1; };
class B_G_Soldier_UAV_lxWS: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_G_UAV_02_IED_lxWS: UAV_02_IED_Base_lxWS { scope = 1; scopeCurator = 1; };
class O_G_Offroad_01_armor_base_lxWS: I_G_Offroad_01_armor_base_lxWS { scope = 1; scopeCurator = 1; };
class O_G_Offroad_01_armor_AT_lxWS: I_G_Offroad_01_armor_AT_lxWS { scope = 1; scopeCurator = 1; };
class O_G_Offroad_01_armor_armed_lxWS: I_G_Offroad_01_armor_armed_lxWS { scope = 1; scopeCurator = 1; };
class O_G_Offroad_AA_lxWS: I_G_Offroad_AA_lxWS { scope = 1; scopeCurator = 1; };
class O_G_Soldier_UAV_lxWS: O_G_Soldier_F { scope = 1; scopeCurator = 1; };
class Aegis_I_C_UAV_02_IED_lxWS: UAV_02_IED_Base_lxWS { scope = 1; scopeCurator = 1; };
class B_T_APC_Wheeled_01_mortar_lxWS: APC_Wheeled_01_mortar_base_lxWS { scope = 1; scopeCurator = 1; };
class B_T_APC_Wheeled_01_command_lxWS: APC_Wheeled_01_command_base_lxWS { scope = 1; scopeCurator = 1; };
class B_T_APC_Wheeled_01_atgm_lxWS: APC_Wheeled_01_atgm_base_lxWS { scope = 1; scopeCurator = 1; };
class Aegis_B_T_UAV_02_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class B_D_CTRG_soldier_UAV_lxWS: B_soldier_UAV_F { scope = 1; scopeCurator = 1; };
class B_CTRG_soldier_djella_lxWS: B_CTRG_soldier_GL_LAT_F { scope = 1; scopeCurator = 1; };
class B_CTRG_soldier_djella_stealth_lxWS: B_CTRG_soldier_djella_lxWS { scope = 1; scopeCurator = 1; };
class Aegis_B_CTRG_UAV_02_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class O_T_APC_Tracked_02_30mm_lxWS: O_APC_Tracked_02_30mm_lxWS { scope = 1; scopeCurator = 1; };
class O_T_Truck_02_cargo_lxWS: O_Truck_02_cargo_lxWS { scope = 1; scopeCurator = 1; };
class O_T_Truck_02_flatbed_lxWS: O_Truck_02_flatbed_lxWS { scope = 1; scopeCurator = 1; };
class Aegis_O_T_UAV_02_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class O_ALC_V_Soldier_hex_lxWS: O_V_Soldier_hex_F { scope = 1; scopeCurator = 1; };
class O_ALC_V_Soldier_M_hex_lxWS: O_V_Soldier_M_hex_F { scope = 1; scopeCurator = 1; };
class O_ALC_V_Soldier_Medic_hex_lxWS: O_V_Soldier_Medic_hex_F { scope = 1; scopeCurator = 1; };
class O_ALC_V_Soldier_LAT_hex_lxWS: O_V_Soldier_LAT_hex_F { scope = 1; scopeCurator = 1; };
class C_IDAP_Offroad_lxWS: Offroad_01_base_lxWS { scope = 1; scopeCurator = 1; };
class C_IDAP_Truck_02_cargo_lxWS: Truck_02_cargo_base_lxWS { scope = 1; scopeCurator = 1; };
class C_IDAP_Truck_02_flatbed_lxWS: Truck_02_flatbed_base_lxWS { scope = 1; scopeCurator = 1; };
class C_IDAP_Truck_02_box_lxWS: Truck_02_box_base_lxWS { scope = 1; scopeCurator = 1; };
class I_E_Truck_02_cargo_lxWS: I_Truck_02_cargo_lxWS { scope = 1; scopeCurator = 1; };
class I_E_Truck_02_flatbed_lxWS: I_Truck_02_flatbed_lxWS { scope = 1; scopeCurator = 1; };
class Aegis_I_E_UAV_02_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class Aegis_B_W_UAV_02_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class Aegis_O_R_UAV_02_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class O_GEN_crew_lxWS: O_crew_F { scope = 1; scopeCurator = 1; };
class ION_UAV_01_lxWS: UAV_01_base_F { scope = 1; scopeCurator = 1; };
class ION_UAV_02_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class lxWS_B_ION_UAV_AI_F: B_UAV_AI_F { scope = 1; scopeCurator = 1; };
class B_ION_soldier_UAV_01_lxWS: B_soldier_UAV_F { scope = 1; scopeCurator = 1; };
class B_ION_soldier_UAV_02_lxWS: B_ION_soldier_UAV_01_lxWS { scope = 1; scopeCurator = 1; };
class B_ION_Soldier_lxWS: B_Soldier_F { scope = 1; scopeCurator = 1; };
class B_ION_Soldier_GL_lxWS: B_Soldier_GL_F { scope = 1; scopeCurator = 1; };
class B_ION_TL_lxWS: B_Soldier_TL_F { scope = 1; scopeCurator = 1; };
class B_ION_soldier_AR_lxWS: B_soldier_AR_F { scope = 1; scopeCurator = 1; };
class B_ION_crew_lxWS: B_crew_F { scope = 1; scopeCurator = 1; };
class B_ION_shot_lxWS: B_ION_Soldier_lxWS { scope = 1; scopeCurator = 1; };
class B_ION_marksman_lxWS: B_soldier_M_F { scope = 1; scopeCurator = 1; };
class B_ION_medic_lxWS: B_medic_F { scope = 1; scopeCurator = 1; };
class B_ION_Survivor_lxWS: B_ION_Soldier_lxWS { scope = 1; scopeCurator = 1; };
class B_ION_Helipilot_lxWS: B_Helipilot_F { scope = 1; scopeCurator = 1; };
class B_ION_Story_Givens_lxWS: B_Soldier_TL_F { scope = 1; scopeCurator = 1; };
class B_ION_Quadbike_01_lxWS: B_Quadbike_01_F { scope = 1; scopeCurator = 1; };
class B_ION_APC_Wheeled_01_cannon_lxWS: B_APC_Wheeled_01_cannon_lxWS { scope = 1; scopeCurator = 1; };
class B_ION_APC_Wheeled_01_command_lxWS: APC_Wheeled_01_command_base_lxWS { scope = 1; scopeCurator = 1; };
class B_ION_Offroad_lxWS: Offroad_01_base_lxWS { scope = 1; scopeCurator = 1; };
class B_ION_Offroad_armed_lxWS: Offroad_01_armed_lxWS { scope = 1; scopeCurator = 1; };
class B_ION_Truck_02_covered_lxWS: O_Truck_02_covered_F { scope = 1; scopeCurator = 1; };
class B_ION_Soldier_SG_lxWS: B_ION_Soldier_lxWS { scope = 1; scopeCurator = 1; };
class B_ION_soldier_LAT2_lxWS: B_soldier_LAT2_F { scope = 1; scopeCurator = 1; };
class B_ION_Pickup_hmg_lxWS: Pickup_01_hmg_base_rf { scope = 1; scopeCurator = 1; };
class B_UN_Heli_Transport_02_lxWS: Heli_Transport_02_base_F { scope = 1; scopeCurator = 1; };
class B_UN_crew_lxWS: B_crew_F { scope = 1; scopeCurator = 1; };
class B_UN_Soldier_lxWS: B_Soldier_F { scope = 1; scopeCurator = 1; };
class B_UN_Soldier_TL_lxWS: B_Soldier_TL_F { scope = 1; scopeCurator = 1; };
class B_UN_officer_lxWS: B_officer_F { scope = 1; scopeCurator = 1; };
class B_UN_engineer_lxWS: B_engineer_F { scope = 1; scopeCurator = 1; };
class B_UN_soldier_AR_lxWS: B_soldier_AR_F { scope = 1; scopeCurator = 1; };
class B_UN_medic_lxWS: B_medic_F { scope = 1; scopeCurator = 1; };
class B_UN_Soldier_lite_lxWS: B_Soldier_lite_F { scope = 1; scopeCurator = 1; };
class B_UN_Soldier_unarmed_lxWS: B_UN_Soldier_lxWS { scope = 1; scopeCurator = 1; };
class B_UN_survivor_lxWS: B_UN_Soldier_lxWS { scope = 1; scopeCurator = 1; };
class B_UN_soldier_repair_lxWS: B_soldier_repair_F { scope = 1; scopeCurator = 1; };
class B_UN_Helipilot_lxWS: B_Helipilot_F { scope = 1; scopeCurator = 1; };
class B_MBT_03_cannon_lxWS: I_MBT_03_cannon_F { scope = 1; scopeCurator = 1; };
class B_UN_Truck_01_fuel_lxWS: B_Truck_01_fuel_F { scope = 1; scopeCurator = 1; };
class B_UN_Truck_01_mover_lxWS: B_Truck_01_mover_F { scope = 1; scopeCurator = 1; };
class B_UN_Truck_01_box_lxWS: B_Truck_01_box_F { scope = 1; scopeCurator = 1; };
class B_UN_Truck_01_Repair_lxWS: B_Truck_01_Repair_F { scope = 1; scopeCurator = 1; };
class B_UN_Truck_01_ammo_lxWS: B_Truck_01_ammo_F { scope = 1; scopeCurator = 1; };
class B_UN_Truck_01_transport_lxWS: B_Truck_01_transport_F { scope = 1; scopeCurator = 1; };
class B_UN_Truck_01_covered_lxWS: B_Truck_01_covered_F { scope = 1; scopeCurator = 1; };
class B_UN_Truck_01_medical_lxWS: B_Truck_01_medical_F { scope = 1; scopeCurator = 1; };
class B_UN_MRAP_01_lxWS: B_MRAP_01_F { scope = 1; scopeCurator = 1; };
class B_UN_APC_Wheeled_01_cannon_lxWS: B_APC_Wheeled_01_cannon_lxWS { scope = 1; scopeCurator = 1; };
class B_UN_APC_Wheeled_01_command_lxWS: APC_Wheeled_01_command_base_lxWS { scope = 1; scopeCurator = 1; };
class B_UN_Offroad_lxWS: Offroad_01_base_lxWS { scope = 1; scopeCurator = 1; };
class B_UN_Offroad_Armor_lxWS: Offroad_01_armor_base_lxWS { scope = 1; scopeCurator = 1; };
class B_UN_Soldier_GL_lxWS: B_Soldier_GL_F { scope = 1; scopeCurator = 1; };
class B_UN_HeavyGunner_lxWS: B_UN_soldier_AR_lxWS { scope = 1; scopeCurator = 1; };
class B_UN_soldier_LAT2_lxWS: B_soldier_LAT2_F { scope = 1; scopeCurator = 1; };
class B_D_VTOL_01_armed_lxWS: B_T_VTOL_01_armed_F { scope = 1; scopeCurator = 1; };
class B_D_VTOL_01_infantry_lxWS: B_T_VTOL_01_infantry_F { scope = 1; scopeCurator = 1; };
class B_D_VTOL_01_vehicle_lxWS: B_T_VTOL_01_vehicle_F { scope = 1; scopeCurator = 1; };
class B_D_Plane_CAS_01_dynamicLoadout_lxWS: B_Plane_CAS_01_dynamicLoadout_F { scope = 1; scopeCurator = 1; };
class B_D_Soldier_A_lxWS: B_Soldier_A_F { scope = 1; scopeCurator = 1; };
class B_D_soldier_AAR_lxWS: B_soldier_AAR_F { scope = 1; scopeCurator = 1; };
class B_D_support_AMG_lxWS: B_support_AMG_F { scope = 1; scopeCurator = 1; };
class B_D_support_AMort_lxWS: B_support_AMort_F { scope = 1; scopeCurator = 1; };
class B_D_soldier_AAA_lxWS: B_soldier_AAA_F { scope = 1; scopeCurator = 1; };
class B_D_soldier_AAT_lxWS: B_soldier_AAT_F { scope = 1; scopeCurator = 1; };
class B_D_soldier_AR_lxWS: B_soldier_AR_F { scope = 1; scopeCurator = 1; };
class B_D_medic_lxWS: B_medic_F { scope = 1; scopeCurator = 1; };
class B_D_crew_lxWS: B_crew_F { scope = 1; scopeCurator = 1; };
class B_D_HeliPilot_lxWS: B_Helipilot_F { scope = 1; scopeCurator = 1; };
class B_D_Pilot_lxWS: B_T_Pilot_F { scope = 1; scopeCurator = 1; };
class B_D_engineer_lxWS: B_engineer_F { scope = 1; scopeCurator = 1; };
class B_D_soldier_exp_lxWS: B_soldier_exp_F { scope = 1; scopeCurator = 1; };
class B_D_Soldier_GL_lxWS: B_Soldier_GL_F { scope = 1; scopeCurator = 1; };
class B_D_support_GMG_lxWS: B_support_GMG_F { scope = 1; scopeCurator = 1; };
class B_D_support_MG_lxWS: B_support_MG_F { scope = 1; scopeCurator = 1; };
class B_D_support_Mort_lxWS: B_support_Mort_F { scope = 1; scopeCurator = 1; };
class B_D_soldier_M_lxWS: B_soldier_M_F { scope = 1; scopeCurator = 1; };
class B_D_soldier_mine_lxWS: B_soldier_mine_F { scope = 1; scopeCurator = 1; };
class B_D_soldier_AA_lxWS: B_soldier_AA_F { scope = 1; scopeCurator = 1; };
class B_D_soldier_AT_lxWS: B_soldier_AT_F { scope = 1; scopeCurator = 1; };
class B_D_officer_lxWS: B_officer_F { scope = 1; scopeCurator = 1; };
class B_D_soldier_PG_lxWS: B_soldier_PG_F { scope = 1; scopeCurator = 1; };
class B_D_soldier_repair_lxWS: B_soldier_repair_F { scope = 1; scopeCurator = 1; };
class B_D_Soldier_lxWS: B_Soldier_F { scope = 1; scopeCurator = 1; };
class B_D_soldier_LAT_lxWS: B_soldier_LAT_F { scope = 1; scopeCurator = 1; };
class B_D_soldier_LAT2_lxWS: B_soldier_LAT2_F { scope = 1; scopeCurator = 1; };
class B_D_Soldier_lite_lxWS: B_Soldier_lite_F { scope = 1; scopeCurator = 1; };
class B_D_Soldier_unarmed_lxWS: B_Soldier_unarmed_F { scope = 1; scopeCurator = 1; };
class B_D_Soldier_SL_lxWS: B_Soldier_SL_F { scope = 1; scopeCurator = 1; };
class B_D_Survivor_lxWS: B_Survivor_F { scope = 1; scopeCurator = 1; };
class B_D_Soldier_TL_lxWS: B_Soldier_TL_F { scope = 1; scopeCurator = 1; };
class B_D_soldier_UAV01_lxWS: B_soldier_UAV_F { scope = 1; scopeCurator = 1; };
class B_D_soldier_UAV02_lxWS: B_soldier_UAV_lxWS { scope = 1; scopeCurator = 1; };
class B_D_recon_exp_lxWS: B_recon_exp_F { scope = 1; scopeCurator = 1; };
class B_D_recon_JTAC_lxWS: B_recon_JTAC_F { scope = 1; scopeCurator = 1; };
class B_D_recon_M_lxWS: B_recon_M_F { scope = 1; scopeCurator = 1; };
class B_D_recon_medic_lxWS: B_recon_medic_F { scope = 1; scopeCurator = 1; };
class B_D_recon_lxWS: B_recon_F { scope = 1; scopeCurator = 1; };
class B_D_recon_LAT_lxWS: B_recon_LAT_F { scope = 1; scopeCurator = 1; };
class B_D_recon_TL_lxWS: B_recon_TL_F { scope = 1; scopeCurator = 1; };
class B_D_Fighter_Pilot_F: B_Fighter_Pilot_F { scope = 1; scopeCurator = 1; };
class B_D_APC_Tracked_01_aa_lxWS: B_APC_Tracked_01_AA_F { scope = 1; scopeCurator = 1; };
class B_D_APC_Tracked_01_CRV_lxWS: B_APC_Tracked_01_CRV_F { scope = 1; scopeCurator = 1; };
class B_D_APC_Tracked_01_rcws_lxWS: B_APC_Tracked_01_rcws_F { scope = 1; scopeCurator = 1; };
class B_D_MBT_01_arty_lxWS: B_MBT_01_arty_F { scope = 1; scopeCurator = 1; };
class B_D_MBT_01_mlrs_lxWS: B_MBT_01_mlrs_F { scope = 1; scopeCurator = 1; };
class B_D_Truck_01_transport_lxWS: B_Truck_01_transport_F { scope = 1; scopeCurator = 1; };
class B_D_Truck_01_covered_lxWS: B_Truck_01_covered_F { scope = 1; scopeCurator = 1; };
class B_D_Truck_01_mover_lxWS: B_Truck_01_mover_F { scope = 1; scopeCurator = 1; };
class B_D_Truck_01_ammo_lxWS: B_Truck_01_ammo_F { scope = 1; scopeCurator = 1; };
class B_D_Truck_01_box_lxWS: B_Truck_01_box_F { scope = 1; scopeCurator = 1; };
class B_D_Truck_01_cargo_lxWS: B_Truck_01_cargo_F { scope = 1; scopeCurator = 1; };
class B_D_Truck_01_flatbed_lxWS: B_Truck_01_flatbed_F { scope = 1; scopeCurator = 1; };
class B_D_Truck_01_fuel_lxWS: B_Truck_01_fuel_F { scope = 1; scopeCurator = 1; };
class B_D_Truck_01_medical_lxWS: B_Truck_01_medical_F { scope = 1; scopeCurator = 1; };
class B_D_Truck_01_Repair_lxWS: B_Truck_01_Repair_F { scope = 1; scopeCurator = 1; };
class B_D_MBT_01_cannon_lxWS: B_MBT_01_cannon_F { scope = 1; scopeCurator = 1; };
class B_D_MBT_01_TUSK_lxWS: B_MBT_01_TUSK_F { scope = 1; scopeCurator = 1; };
class B_D_static_AT_lxWS: B_static_AT_F { scope = 1; scopeCurator = 1; };
class B_D_static_AA_lxWS: B_static_AA_F { scope = 1; scopeCurator = 1; };
class B_D_Mortar_01_lxWS: B_Mortar_01_F { scope = 1; scopeCurator = 1; };
class B_D_Quadbike_01_lxWS: B_Quadbike_01_F { scope = 1; scopeCurator = 1; };
class B_D_MRAP_01_lxWS: B_MRAP_01_F { scope = 1; scopeCurator = 1; };
class B_D_MRAP_01_gmg_lxWS: B_MRAP_01_gmg_F { scope = 1; scopeCurator = 1; };
class B_D_MRAP_01_hmg_lxWS: B_MRAP_01_hmg_F { scope = 1; scopeCurator = 1; };
class B_D_UGV_01_lxWS: B_UGV_01_F { scope = 1; scopeCurator = 1; };
class B_D_UGV_01_rcws_lxWS: B_UGV_01_rcws_F { scope = 1; scopeCurator = 1; };
class B_D_APC_Wheeled_01_cannon_lxWS: B_APC_Wheeled_01_cannon_F { scope = 1; scopeCurator = 1; };
class B_D_APC_Wheeled_01_mortar_lxWS: APC_Wheeled_01_mortar_base_lxWS { scope = 1; scopeCurator = 1; };
class B_D_APC_Wheeled_01_command_lxWS: APC_Wheeled_01_command_base_lxWS { scope = 1; scopeCurator = 1; };
class B_D_APC_Wheeled_01_atgm_lxWS: APC_Wheeled_01_atgm_base_lxWS { scope = 1; scopeCurator = 1; };
class I_SFIA_soldier_lxWS: I_soldier_F { scope = 1; scopeCurator = 1; };
class I_SFIA_Soldier_universal_lxWS: I_SFIA_soldier_lxWS { scope = 1; scopeCurator = 1; };
class I_SFIA_Soldier_TL_lxWS: I_Soldier_TL_F { scope = 1; scopeCurator = 1; };
class I_SFIA_Soldier_GL_lxWS: I_Soldier_GL_F { scope = 1; scopeCurator = 1; };
class I_SFIA_Soldier_AR_lxWS: I_Soldier_AR_F { scope = 1; scopeCurator = 1; };
class I_SFIA_officer_lxWS: I_officer_F { scope = 1; scopeCurator = 1; };
class I_SFIA_sharpshooter_lxWS: I_G_Sharpshooter_F { scope = 1; scopeCurator = 1; };
class I_SFIA_crew_lxWS: I_crew_F { scope = 1; scopeCurator = 1; };
class I_SFIA_pilot_lxWS: I_pilot_F { scope = 1; scopeCurator = 1; };
class I_SFIA_soldier_at_lxWS: I_Soldier_AT_F { scope = 1; scopeCurator = 1; };
class I_SFIA_soldier_aa_lxWS: I_Soldier_AA_F { scope = 1; scopeCurator = 1; };
class I_SFIA_medic_lxWS: I_G_medic_F { scope = 1; scopeCurator = 1; };
class I_SFIA_exp_lxWS: I_G_Soldier_exp_F { scope = 1; scopeCurator = 1; };
class I_SFIA_repair_lxWS: I_Soldier_repair_F { scope = 1; scopeCurator = 1; };
class I_SFIA_soldier_unarmed_lxWS: I_SFIA_soldier_lxWS { scope = 1; scopeCurator = 1; };
class I_SFIA_survivor_lxWS: I_SFIA_soldier_lxWS { scope = 1; scopeCurator = 1; };
class I_SFIA_Soldier_AAT_lxWS: I_Soldier_AAT_F { scope = 1; scopeCurator = 1; };
class I_SFIA_Soldier_AAA_lxWS: I_Soldier_AAA_F { scope = 1; scopeCurator = 1; };
class I_SFIA_APC_Tracked_02_30mm_lxWS: O_T_APC_Tracked_02_30mm_lxWS { scope = 1; scopeCurator = 1; };
class APC_Wheeled_02_unarmed_base_lxws: APC_Wheeled_02_base_v2_F { scope = 1; scopeCurator = 1; };
class I_SFIA_APC_Wheeled_02_unarmed_lxWS: APC_Wheeled_02_unarmed_base_lxws { scope = 1; scopeCurator = 1; };
class APC_Wheeled_02_hmg_base_lxws: APC_Wheeled_02_base_v2_F { scope = 1; scopeCurator = 1; };
class I_SFIA_APC_Wheeled_02_hmg_lxWS: APC_Wheeled_02_hmg_base_lxws { scope = 1; scopeCurator = 1; };
class I_SFIA_APC_Tracked_02_cannon_lxWS: O_APC_Tracked_02_cannon_F { scope = 1; scopeCurator = 1; };
class I_SFIA_APC_Tracked_02_AA_lxWS: O_APC_Tracked_02_AA_F { scope = 1; scopeCurator = 1; };
class I_SFIA_MBT_02_cannon_lxWS: O_MBT_02_cannon_F { scope = 1; scopeCurator = 1; };
class I_SFIA_Mortar_lxWS: I_Mortar_01_F { scope = 1; scopeCurator = 1; };
class I_SFIA_HMG_02_lxWS: I_G_HMG_02_F { scope = 1; scopeCurator = 1; };
class I_SFIA_HMG_02_high_lxWS: I_G_HMG_02_high_F { scope = 1; scopeCurator = 1; };
class I_SFIA_Offroad_lxWS: Offroad_01_base_lxWS { scope = 1; scopeCurator = 1; };
class I_SFIA_Offroad_AT_lxWS: Offroad_01_AT_lxWS { scope = 1; scopeCurator = 1; };
class I_SFIA_Offroad_armed_lxWS: Offroad_01_armed_lxWS { scope = 1; scopeCurator = 1; };
class I_SFIA_Offroad_AA_lxWS: Offroad_01_aa_lxWS { scope = 1; scopeCurator = 1; };
class I_SFIA_Truck_02_transport_lxWS: O_Truck_02_transport_F { scope = 1; scopeCurator = 1; };
class I_SFIA_Truck_02_flatbed_lxWS: Truck_02_flatbed_base_lxWS { scope = 1; scopeCurator = 1; };
class I_SFIA_Truck_02_aa_lxWS: Truck_02_aa_base_lxWS { scope = 1; scopeCurator = 1; };
class I_SFIA_Truck_02_cargo_lxWS: Truck_02_cargo_base_lxWS { scope = 1; scopeCurator = 1; };
class I_SFIA_Truck_02_covered_lxWS: O_Truck_02_covered_F { scope = 1; scopeCurator = 1; };
class I_SFIA_Truck_02_box_lxWS: Truck_02_box_base_lxWS { scope = 1; scopeCurator = 1; };
class I_SFIA_Truck_02_Ammo_lxWS: Truck_02_Ammo_base_lxWS { scope = 1; scopeCurator = 1; };
class I_SFIA_Truck_02_MRL_lxWS: I_Truck_02_MRL_F { scope = 1; scopeCurator = 1; };
class I_SFIA_Truck_02_fuel_lxWS: O_Truck_02_fuel_F { scope = 1; scopeCurator = 1; };
class I_SFIA_ZU23_lxWS: zu23_base_lxWS { scope = 1; scopeCurator = 1; };
class I_SFIA_soldier_lite_lxWS: I_SFIA_soldier_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_soldier_lxWS: I_SFIA_soldier_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_Soldier_universal_lxWS: I_SFIA_Soldier_universal_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_Soldier_TL_lxWS: I_SFIA_Soldier_TL_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_Soldier_GL_lxWS: I_SFIA_Soldier_GL_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_Soldier_AR_lxWS: I_SFIA_Soldier_AR_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_officer_lxWS: I_SFIA_officer_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_sharpshooter_lxWS: I_SFIA_sharpshooter_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_crew_lxWS: I_SFIA_crew_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_pilot_lxWS: I_SFIA_pilot_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_soldier_at_lxWS: I_SFIA_soldier_at_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_soldier_aa_lxWS: I_SFIA_soldier_aa_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_medic_lxWS: I_SFIA_medic_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_exp_lxWS: I_SFIA_exp_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_repair_lxWS: I_SFIA_repair_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_soldier_unarmed_lxWS: I_SFIA_soldier_unarmed_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_survivor_lxWS: I_SFIA_survivor_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_Soldier_AAT_lxWS: I_SFIA_Soldier_AAT_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_Soldier_AAA_lxWS: I_SFIA_Soldier_AAA_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_APC_Tracked_02_30mm_lxWS: I_SFIA_APC_Tracked_02_30mm_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_APC_Wheeled_02_unarmed_lxWS: I_SFIA_APC_Wheeled_02_unarmed_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_APC_Wheeled_02_hmg_lxWS: I_SFIA_APC_Wheeled_02_hmg_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_APC_Tracked_02_cannon_lxWS: I_SFIA_APC_Tracked_02_cannon_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_APC_Tracked_02_AA_lxWS: I_SFIA_APC_Tracked_02_AA_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_MBT_02_cannon_lxWS: I_SFIA_MBT_02_cannon_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_Mortar_lxWS: I_SFIA_Mortar_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_HMG_02_lxWS: I_SFIA_HMG_02_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_HMG_02_high_lxWS: I_SFIA_HMG_02_high_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_Offroad_lxWS: I_SFIA_Offroad_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_Offroad_AT_lxWS: I_SFIA_Offroad_AT_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_Offroad_armed_lxWS: I_SFIA_Offroad_armed_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_Offroad_aa_lxWS: I_SFIA_Offroad_AA_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_Truck_02_transport_lxWS: I_SFIA_Truck_02_transport_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_Truck_02_flatbed_lxWS: I_SFIA_Truck_02_flatbed_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_Truck_02_aa_lxWS: I_SFIA_Truck_02_aa_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_Truck_02_cargo_lxWS: I_SFIA_Truck_02_cargo_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_Truck_02_covered_lxWS: I_SFIA_Truck_02_covered_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_Truck_02_box_lxWS: I_SFIA_Truck_02_box_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_Truck_02_Ammo_lxWS: I_SFIA_Truck_02_Ammo_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_Truck_02_MRL_lxWS: I_SFIA_Truck_02_MRL_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_Truck_02_fuel_lxWS: I_SFIA_Truck_02_fuel_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_ZU23_lxWS: I_SFIA_ZU23_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_ZU23_stripped_lxWS: O_SFIA_ZU23_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_HeavyGunner_lxWS: O_SFIA_Soldier_AR_lxWS { scope = 1; scopeCurator = 1; };
class O_SFIA_soldier_lite_lxWS: O_SFIA_soldier_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_UAV_02_IED_lxWS: UAV_02_IED_Base_lxWS { scope = 1; scopeCurator = 1; };
class I_SFIA_scout_lxWS: I_C_Soldier_Bandit_5_F { scope = 1; scopeCurator = 1; };
class I_SFIA_watcher_lxWS: I_C_Soldier_Bandit_4_F { scope = 1; scopeCurator = 1; };
class I_SFIA_enforcer_lxWS: I_C_Soldier_Para_2_F { scope = 1; scopeCurator = 1; };
class I_SFIA_hireling_lxWS: I_C_Soldier_Bandit_2_F { scope = 1; scopeCurator = 1; };
class I_SFIA_medic2_lxWS: I_C_Soldier_Bandit_1_F { scope = 1; scopeCurator = 1; };
class I_SFIA_thug_lxWS: I_SFIA_scout_lxWS { scope = 1; scopeCurator = 1; };
class I_SFIA_deserter_lxWS: I_SFIA_soldier_lxWS { scope = 1; scopeCurator = 1; };
class I_SFIA_defector_lxWS: I_SFIA_soldier_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_scout_lxWS: I_SFIA_scout_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_watcher_lxWS: I_SFIA_watcher_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_enforcer_lxWS: I_SFIA_enforcer_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_hireling_lxWS: I_SFIA_hireling_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_medic2_lxWS: I_SFIA_medic2_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_thug_lxWS: I_SFIA_thug_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_deserter_lxWS: I_SFIA_deserter_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_defector_lxWS: I_SFIA_defector_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_HMG_gunner_lxWS: I_Tura_deserter_lxWS { scope = 1; scopeCurator = 1; };
class I_PMC_Soldier_01_lxWS: B_Soldier_F { scope = 1; scopeCurator = 1; };
class I_PMC_Soldier_02_lxWS: I_PMC_Soldier_01_lxWS { scope = 1; scopeCurator = 1; };
class I_PMC_Soldier_03_lxWS: I_PMC_Soldier_01_lxWS { scope = 1; scopeCurator = 1; };
class I_PMC_Story_Gustavo_lxWS: I_PMC_Soldier_01_lxWS { scope = 1; scopeCurator = 1; };
class I_SFIA_Said_lxWS: I_SFIA_officer_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_crew_lxWS: I_SFIA_crew_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_deserter_EXT_R5GL_lxWS: I_SFIA_deserter_lxWS { scope = 1; scopeCurator = 1; };
class I_SFIA_scout_EXT_Galat_lxWS: I_SFIA_scout_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_enforcer_EXT_Zafir_lxWS: I_SFIA_enforcer_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_enforcer_EXT_RPK12_lxWS: I_SFIA_enforcer_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_deserter_EXT_AK12U_lxWS: I_SFIA_deserter_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_scout_EXT_DMR_Hunter_lxWS: I_SFIA_scout_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_medic2_EXT_HShotgun_lxWS: I_SFIA_medic2_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_scout_EXT_DMR_camo_lxWS: I_SFIA_scout_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_deserter_EXT_AKM_lxWS: I_SFIA_deserter_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_hireling_EXT_RPG7_lxWS: I_SFIA_hireling_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_watcher_EXT_AKS_lxWS: I_SFIA_watcher_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_watcher_EXT_AKM_lxWS: I_SFIA_watcher_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_APC_Wheeled_02_hmg_lxWS: I_SFIA_APC_Wheeled_02_hmg_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_Mortar_lxWS: I_SFIA_Mortar_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_HMG_02_lxWS: I_SFIA_HMG_02_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_HMG_02_high_lxWS: I_SFIA_HMG_02_high_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_Offroad_armor_lxWS: Offroad_01_armor_base_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_Offroad_armor_AT_lxWS: Offroad_01_armor_AT_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_Offroad_armor_armed_lxWS: Offroad_01_armor_armed_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_Offroad_armor_AA_lxWS: Offroad_01_armor_aa_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_Truck_02_aa_lxWS: O_SFIA_Truck_02_aa_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_ZU23_lxWS: O_SFIA_ZU23_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_soldier_UAV_lxWS: I_Tura_deserter_lxWS { scope = 1; scopeCurator = 1; };
class I_Tura_HeavyGunner_lxWS: I_Tura_deserter_lxWS { scope = 1; scopeCurator = 1; };
class B_Tura_UAV_02_IED_lxWS: UAV_02_IED_Base_lxWS { scope = 1; scopeCurator = 1; };
class B_Tura_scout_lxWS: I_SFIA_scout_lxWS { scope = 1; scopeCurator = 1; };
class B_Tura_watcher_lxWS: I_SFIA_watcher_lxWS { scope = 1; scopeCurator = 1; };
class B_Tura_enforcer_lxWS: I_SFIA_enforcer_lxWS { scope = 1; scopeCurator = 1; };
class B_Tura_hireling_lxWS: I_SFIA_hireling_lxWS { scope = 1; scopeCurator = 1; };
class B_Tura_medic2_lxWS: I_SFIA_medic2_lxWS { scope = 1; scopeCurator = 1; };
class B_Tura_thug_lxWS: I_SFIA_thug_lxWS { scope = 1; scopeCurator = 1; };
class B_Tura_deserter_lxWS: I_SFIA_deserter_lxWS { scope = 1; scopeCurator = 1; };
class B_Tura_defector_lxWS: I_SFIA_defector_lxWS { scope = 1; scopeCurator = 1; };
class B_Tura_Mortar_lxWS: I_Tura_Mortar_lxWS { scope = 1; scopeCurator = 1; };
class B_Tura_HMG_02_lxWS: I_Tura_HMG_02_lxWS { scope = 1; scopeCurator = 1; };
class B_Tura_HMG_02_high_lxWS: I_Tura_HMG_02_high_lxWS { scope = 1; scopeCurator = 1; };
class B_Tura_Offroad_armor_lxWS: I_Tura_Offroad_armor_lxWS { scope = 1; scopeCurator = 1; };
class B_Tura_Offroad_armor_AT_lxWS: I_Tura_Offroad_armor_AT_lxWS { scope = 1; scopeCurator = 1; };
class B_Tura_Offroad_armor_armed_lxWS: I_Tura_Offroad_armor_armed_lxWS { scope = 1; scopeCurator = 1; };
class B_Tura_Offroad_armor_AA_lxWS: I_Tura_Offroad_armor_AA_lxWS { scope = 1; scopeCurator = 1; };
class B_Tura_Truck_02_aa_lxWS: O_SFIA_Truck_02_aa_lxWS { scope = 1; scopeCurator = 1; };
class B_Tura_ZU23_lxWS: O_SFIA_ZU23_lxWS { scope = 1; scopeCurator = 1; };
class B_Tura_soldier_UAV_lxWS: B_Tura_deserter_lxWS { scope = 1; scopeCurator = 1; };
class B_Tura_HeavyGunner_lxWS: I_Tura_HeavyGunner_lxWS { scope = 1; scopeCurator = 1; };
class O_Tura_UAV_02_IED_lxWS: UAV_02_IED_Base_lxWS { scope = 1; scopeCurator = 1; };
class O_Tura_scout_lxWS: I_SFIA_scout_lxWS { scope = 1; scopeCurator = 1; };
class O_Tura_watcher_lxWS: I_SFIA_watcher_lxWS { scope = 1; scopeCurator = 1; };
class O_Tura_enforcer_lxWS: I_SFIA_enforcer_lxWS { scope = 1; scopeCurator = 1; };
class O_Tura_hireling_lxWS: I_SFIA_hireling_lxWS { scope = 1; scopeCurator = 1; };
class O_Tura_medic2_lxWS: I_SFIA_medic2_lxWS { scope = 1; scopeCurator = 1; };
class O_Tura_thug_lxWS: I_SFIA_thug_lxWS { scope = 1; scopeCurator = 1; };
class O_Tura_deserter_lxWS: I_SFIA_deserter_lxWS { scope = 1; scopeCurator = 1; };
class O_Tura_defector_lxWS: I_SFIA_defector_lxWS { scope = 1; scopeCurator = 1; };
class O_Tura_Mortar_lxWS: I_Tura_Mortar_lxWS { scope = 1; scopeCurator = 1; };
class O_Tura_HMG_02_lxWS: I_Tura_HMG_02_lxWS { scope = 1; scopeCurator = 1; };
class O_Tura_HMG_02_high_lxWS: I_Tura_HMG_02_high_lxWS { scope = 1; scopeCurator = 1; };
class O_Tura_Offroad_armor_lxWS: I_Tura_Offroad_armor_lxWS { scope = 1; scopeCurator = 1; };
class O_Tura_Offroad_armor_AT_lxWS: I_Tura_Offroad_armor_AT_lxWS { scope = 1; scopeCurator = 1; };
class O_Tura_Offroad_armor_armed_lxWS: I_Tura_Offroad_armor_armed_lxWS { scope = 1; scopeCurator = 1; };
class O_Tura_Offroad_armor_AA_lxWS: I_Tura_Offroad_armor_AA_lxWS { scope = 1; scopeCurator = 1; };
class O_Tura_Truck_02_aa_lxWS: O_SFIA_Truck_02_aa_lxWS { scope = 1; scopeCurator = 1; };
class O_Tura_ZU23_lxWS: O_SFIA_ZU23_lxWS { scope = 1; scopeCurator = 1; };
class O_Tura_soldier_UAV_lxWS: O_Tura_deserter_lxWS { scope = 1; scopeCurator = 1; };
class O_Tura_HeavyGunner_lxWS: I_Tura_HeavyGunner_lxWS { scope = 1; scopeCurator = 1; };
class O_A_officer_lxWS: O_officer_F { scope = 1; scopeCurator = 1; };
class O_A_Soldier_TL_lxWS: O_Soldier_TL_F { scope = 1; scopeCurator = 1; };
class O_A_Soldier_lxWS: O_Soldier_F { scope = 1; scopeCurator = 1; };
class O_A_Soldier_GL_lxWS: O_Soldier_GL_F { scope = 1; scopeCurator = 1; };
class O_A_medic_lxWS: O_medic_F { scope = 1; scopeCurator = 1; };
class O_A_crew_lxWS: O_crew_F { scope = 1; scopeCurator = 1; };
class O_A_Soldier_AR_lxWS: O_Soldier_AR_F { scope = 1; scopeCurator = 1; };
class O_A_Soldier_LAT_lxWS: O_Soldier_LAT_F { scope = 1; scopeCurator = 1; };
class O_A_HeavyGunner_lxWS: O_A_Soldier_AR_lxWS { scope = 1; scopeCurator = 1; };
class O_ALC_Soldier_lxWS: O_A_Soldier_lxWS { scope = 1; scopeCurator = 1; };
class O_ALC_Soldier_UAV_lxWS: O_ALC_Soldier_lxWS { scope = 1; scopeCurator = 1; };
class O_ALC_Soldier_AR_lxWS: O_A_Soldier_AR_lxWS { scope = 1; scopeCurator = 1; };
class O_ALC_Soldier_GL_lxWS: O_A_Soldier_GL_lxWS { scope = 1; scopeCurator = 1; };
class Aegis_B_CTRG_UAV_02_tna_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class Aegis_B_A_UAV_02_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class Aegis_B_A_UAV_02_tna_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class Aegis_B_A_UAV_02_wdl_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class Aegis_O_R_UAV_02_ard_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class Aegis_I_Raven_UAV_02_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class Aegis_O_Raven_UAV_02_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class Aegis_B_E_UAV_02_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class C_Tak_01_A_lxWS: C_Man_casual_1_F_afro { scope = 1; scopeCurator = 1; };
class C_Tak_01_B_lxWS: C_Tak_01_A_lxWS { scope = 1; scopeCurator = 1; };
class C_Tak_01_C_lxWS: C_Tak_01_A_lxWS { scope = 1; scopeCurator = 1; };
class C_Tak_02_A_lxWS: C_Tak_01_A_lxWS { scope = 1; scopeCurator = 1; };
class C_Tak_02_B_lxWS: C_Tak_02_A_lxWS { scope = 1; scopeCurator = 1; };
class C_Tak_02_C_lxWS: C_Tak_02_A_lxWS { scope = 1; scopeCurator = 1; };
class C_Tak_03_A_lxWS: C_Tak_01_A_lxWS { scope = 1; scopeCurator = 1; };
class C_Tak_03_B_lxWS: C_Tak_02_A_lxWS { scope = 1; scopeCurator = 1; };
class C_Tak_03_C_lxWS: C_Tak_02_A_lxWS { scope = 1; scopeCurator = 1; };
class C_Djella_01_lxWS: C_Tak_02_A_lxWS { scope = 1; scopeCurator = 1; };
class C_Djella_02_lxWS: C_Djella_01_lxWS { scope = 1; scopeCurator = 1; };
class C_Djella_02a_lxWS: C_Djella_01_lxWS { scope = 1; scopeCurator = 1; };
class C_Djella_03_lxWS: C_Djella_01_lxWS { scope = 1; scopeCurator = 1; };
class C_Djella_04_lxWS: C_Djella_01_lxWS { scope = 1; scopeCurator = 1; };
class C_Djella_05_lxWS: C_Djella_01_lxWS { scope = 1; scopeCurator = 1; };
class C_Djella_06_lxWS: C_Djella_01_lxWS { scope = 1; scopeCurator = 1; };
class C_Djella_07_lxWS: C_Djella_01_lxWS { scope = 1; scopeCurator = 1; };
class CivilianPresence_C_Tak_01_A_lxWS: C_Tak_01_A_lxWS { scope = 1; scopeCurator = 1; };
class CivilianPresence_C_Tak_01_B_lxWS: C_Tak_01_B_lxWS { scope = 1; scopeCurator = 1; };
class CivilianPresence_C_Tak_01_C_lxWS: C_Tak_01_C_lxWS { scope = 1; scopeCurator = 1; };
class CivilianPresence_C_Tak_02_A_lxWS: C_Tak_02_A_lxWS { scope = 1; scopeCurator = 1; };
class CivilianPresence_C_Tak_02_B_lxWS: C_Tak_02_B_lxWS { scope = 1; scopeCurator = 1; };
class CivilianPresence_C_Tak_02_C_lxWS: C_Tak_02_C_lxWS { scope = 1; scopeCurator = 1; };
class CivilianPresence_C_Tak_03_A_lxWS: C_Tak_03_A_lxWS { scope = 1; scopeCurator = 1; };
class CivilianPresence_C_Tak_03_B_lxWS: C_Tak_03_B_lxWS { scope = 1; scopeCurator = 1; };
class CivilianPresence_C_Tak_03_C_lxWS: C_Tak_03_C_lxWS { scope = 1; scopeCurator = 1; };
class CivilianPresence_C_Djella_01_lxWS: C_Djella_01_lxWS { scope = 1; scopeCurator = 1; };
class CivilianPresence_C_Djella_02a_lxWS: C_Djella_02a_lxWS { scope = 1; scopeCurator = 1; };
class CivilianPresence_C_Djella_03_lxWS: C_Djella_03_lxWS { scope = 1; scopeCurator = 1; };
class CivilianPresence_C_Djella_04_lxWS: C_Djella_04_lxWS { scope = 1; scopeCurator = 1; };
class CivilianPresence_C_Djella_05_lxWS: C_Djella_05_lxWS { scope = 1; scopeCurator = 1; };
class CivilianPresence_C_Djella_06_lxWS: C_Djella_06_lxWS { scope = 1; scopeCurator = 1; };
class CivilianPresence_C_Djella_07_lxWS: C_Djella_07_lxWS { scope = 1; scopeCurator = 1; };
class Atlas_B_A_UAV_02_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class Atlas_B_A_UAV_02_ard_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class Atlas_B_A_UAV_02_trp_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class Atlas_I_I_UAV_02_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class Opf_O_S_UAV_02_IED_lxWS: UAV_02_IED_Base_lxWS { scope = 1; scopeCurator = 1; };
class Opf_I_I_UAV_02_IED_lxWS: UAV_02_IED_Base_lxWS { scope = 1; scopeCurator = 1; };
class Opf_B_P_UAV_02_IED_lxWS: UAV_02_IED_Base_lxWS { scope = 1; scopeCurator = 1; };
class B_UAV_02_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class B_APC_Wheeled_02_unarmed_lxWS: APC_Wheeled_02_unarmed_base_lxws { scope = 1; scopeCurator = 1; };
class B_APC_Wheeled_02_hmg_lxWS: APC_Wheeled_02_hmg_base_lxws { scope = 1; scopeCurator = 1; };
class O_UAV_02_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class O_APC_Wheeled_02_unarmed_lxWS: APC_Wheeled_02_unarmed_base_lxws { scope = 1; scopeCurator = 1; };
class O_APC_Wheeled_02_hmg_lxWS: APC_Wheeled_02_hmg_base_lxws { scope = 1; scopeCurator = 1; };
class I_UAV_02_lxWS: UAV_02_Base_lxWS { scope = 1; scopeCurator = 1; };
class I_G_UAV_02_IED_lxWS: UAV_02_IED_Base_lxWS { scope = 1; scopeCurator = 1; };
class B_D_CTRG_Soldier_SG_lxWS: B_ION_Soldier_SG_lxWS { scope = 1; scopeCurator = 1; };
class B_D_CTRG_Soldier_HG_lxWS: B_CTRG_Soldier_AR_tna_F { scope = 1; scopeCurator = 1; };
class B_D_CTRG_Soldier_Exp_lxWS: B_CTRG_Soldier_Exp_tna_F { scope = 1; scopeCurator = 1; };
class B_D_CTRG_Soldier_JTAC_lxWS: B_CTRG_Soldier_JTAC_tna_F { scope = 1; scopeCurator = 1; };
class B_D_CTRG_Soldier_Medic_lxWS: B_CTRG_Soldier_Medic_tna_F { scope = 1; scopeCurator = 1; };
class B_D_CTRG_Soldier_LAT2_lxWS: B_CTRG_Soldier_LAT2_tna_F { scope = 1; scopeCurator = 1; };
class B_D_CTRG_Soldier_lxWS: B_CTRG_Soldier_tna_F { scope = 1; scopeCurator = 1; };
class B_D_CTRG_Soldier_TL_lxWS: B_CTRG_Soldier_TL_tna_F { scope = 1; scopeCurator = 1; };
class B_GEN_crew_lxWS: O_GEN_crew_lxWS { scope = 1; scopeCurator = 1; };
class O_T_APC_Wheeled_02_unarmed_lxWS: O_APC_Wheeled_02_unarmed_lxWS { scope = 1; scopeCurator = 1; };
class O_T_APC_Wheeled_02_hmg_lxWS: O_APC_Wheeled_02_hmg_lxWS { scope = 1; scopeCurator = 1; };
class O_ALC_V_Soldier_TL_hex_lxWS: O_V_Soldier_TL_hex_F { scope = 1; scopeCurator = 1; };
class O_GEN_APC_Wheeled_02_hmg_lxWS: O_SFIA_APC_Wheeled_02_hmg_lxWS { scope = 1; scopeCurator = 1; };
class B_ION_Heli_Light_02_dynamicLoadout_lxWS: O_Heli_Light_02_dynamicLoadout_F { scope = 1; scopeCurator = 1; };
class B_ION_Heli_Light_02_unarmed_lxWS: O_Heli_Light_02_unarmed_F { scope = 1; scopeCurator = 1; };
class B_ION_APC_Wheeled_02_unarmed_lxWS: APC_Wheeled_02_unarmed_base_lxws { scope = 1; scopeCurator = 1; };
class B_ION_APC_Wheeled_02_hmg_lxWS: APC_Wheeled_02_hmg_base_lxws { scope = 1; scopeCurator = 1; };
class B_UNA_APC_Wheeled_02_unarmed_lxWS: APC_Wheeled_02_unarmed_base_lxws { scope = 1; scopeCurator = 1; };
class B_UNA_APC_Wheeled_02_hmg_lxWS: APC_Wheeled_02_hmg_base_lxws { scope = 1; scopeCurator = 1; };
class B_D_Heli_Light_01_dynamicLoadout_lxWS: B_Heli_Light_01_dynamicLoadout_F { scope = 1; scopeCurator = 1; };
class B_D_Heli_Attack_01_dynamicLoadout_lxWS: B_Heli_Attack_01_dynamicLoadout_F { scope = 1; scopeCurator = 1; };
class B_D_Heli_Light_01_lxWS: B_Heli_Light_01_F { scope = 1; scopeCurator = 1; };
class B_D_Heli_Transport_01_lxWS: B_Heli_Transport_01_F { scope = 1; scopeCurator = 1; };
class B_D_Heli_Transport_03_lxWS: B_Heli_Transport_03_F { scope = 1; scopeCurator = 1; };
class B_D_Heli_Transport_03_unarmed_lxWS: B_Heli_Transport_03_unarmed_F { scope = 1; scopeCurator = 1; };
class B_D_APC_Wheeled_02_unarmed_lxWS: B_APC_Wheeled_02_unarmed_lxWS { scope = 1; scopeCurator = 1; };
class B_D_APC_Wheeled_02_hmg_lxWS: B_APC_Wheeled_02_hmg_lxWS { scope = 1; scopeCurator = 1; };
class Aegis_B_D_UAV_02_lxWS: B_UAV_02_lxWS { scope = 1; scopeCurator = 1; };
class I_SFIA_Heli_Attack_02_dynamicLoadout_lxWS: O_Heli_Attack_02_dynamicLoadout_F { scope = 1; scopeCurator = 1; };
class O_SFIA_Heli_Attack_02_dynamicLoadout_lxWS: I_SFIA_Heli_Attack_02_dynamicLoadout_lxWS { scope = 1; scopeCurator = 1; };
class B_D_CTRG_Soldier_M_lxWS: B_CTRG_Soldier_M_tna_F { scope = 1; scopeCurator = 1; };
class B_D_CTRG_Soldier_sniper_lxWS: B_D_CTRG_Soldier_M_lxWS { scope = 1; scopeCurator = 1; };
class B_GEN_APC_Wheeled_02_hmg_lxWS: O_GEN_APC_Wheeled_02_hmg_lxWS { scope = 1; scopeCurator = 1; };
};
