#include "script_component.hpp"
class CfgPatches {
    class ADDON {
        name = QUOTE(COMPONENT);
        units[] = {};
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {
            "synixe_hider_main",
"A3_Aegis_Air_F_Aegis_Plane_CAS_01",
"A3_Aegis_Static_F_Aegis_HMG_02",
"A3_Aegis_Soft_F_Aegis_Van_02",
"A3_Aegis_Air_F_Aegis_Heli_Transport_01",
"A3_Aegis_Characters_F_Aegis",
"A3_Aegis_Soft_F_Aegis_RF_Pickup_01",
"A3_Aegis_Air_F_Aegis_Heli_Transport_04",
"A3_Aegis_Soft_F_Aegis_Offroad_01",
"A3_Aegis_Boat_F_Aegis_Boat_Transport_01",
"A3_Aegis_Air_F_Aegis_Heli_Attack_03",
"A3_Aegis_Soft_F_Aegis_LSV_01",
"A3_Aegis_Air_F_Aegis_Plane_Fighter_03",
"A3_Aegis_Static_F_Aegis_SAM_System_04",
"A3_Aegis_Air_F_Aegis_VTOL_01",
"A3_Aegis_Boat_F_Aegis_Scooter_Transport_01",
"A3_Aegis_Air_F_Aegis_Plane_Fighter_05",
"A3_Aegis_Soft_F_Aegis_Truck_02",
"A3_Aegis_Soft_F_Aegis_UGV_02",
"A3_Aegis_Static_F_Aegis_Designator_01",
"A3_Aegis_Static_F_Aegis_SAM_System_03",
"A3_Aegis_Armor_F_Aegis_MBT_01",
"A3_Aegis_Soft_F_Aegis_Truck_03",
"A3_Aegis_Air_F_Aegis_Plane_Transport_01",
"A3_Aegis_Air_F_Aegis_Heli_Light_03",
"A3_Aegis_Air_F_Aegis_VTOL_02",
"A3_Aegis_Soft_F_Aegis_Van_01",
"A3_Aegis_Boat_F_Aegis_Boat_Civil_02",
"A3_Aegis_Armor_F_Aegis_APC_Wheeled_02",
"A3_Aegis_Static_F_Aegis_AA_01",
"A3_Aegis_Soft_F_Aegis_Offroad_02",
"A3_Aegis_Air_F_Aegis_Plane_Fighter_04",
"A3_Aegis_Air_F_Aegis_Heli_Light_01",
"A3_Aegis_Static_F_Aegis_ZU23",
"A3_Aegis_Air_F_Aegis",
"A3_Aegis_Boat_F_Aegis_Boat_Transport_02",
"A3_Aegis_Static_F_Aegis_Radar_System_01",
"A3_Aegis_Air_F_Aegis_RF_Heli_Light_03",
"A3_Aegis_Armor_F_Aegis_MBT_03",
"A3_Aegis_Static_F_Aegis_AT_01",
"A3_Aegis_Air_F_Aegis_Plane_Fighter_01",
"A3_Aegis_Air_F_Aegis_Plane_Fighter_02",
"A3_Aegis_Boat_F_Aegis_Boat_Civil_01",
"A3_Aegis_Air_F_Aegis_Heli_Attack_02",
"A3_Aegis_Boat_F_Aegis_Boat_Armed_01",
"A3_Aegis_Boat_F_Aegis_SDV_01",
"A3_Aegis_Air_F_Aegis_RF_Heli_Medium_EC",
"A3_Aegis_Air_F_Aegis_Heli_Transport_02",
"A3_Aegis_Animals_F_Aegis",
"A3_Aegis_Air_F_Aegis_Heli_Light_02",
"A3_Aegis_Armor_F_Aegis_APC_Wheeled_01",
"A3_Aegis_Air_F_Aegis_UAV_03",
"A3_Aegis_Armor_F_Aegis_APC_Wheeled_03",
"A3_Aegis_Characters_F_Aegis_RF",
"A3_Aegis_Air_F_Aegis_Plane_CAS_02",
"A3_Aegis_Armor_F_Aegis_APC_Tracked_03",
"A3_Aegis_Soft_F_Aegis_MRAP_01",
"A3_Aegis_Air_F_Aegis_Heli_Transport_03",
"A3_Aegis_Air_F_Aegis_UAV_02",
"A3_Aegis_Air_F_Aegis_UAV_01",
"A3_Aegis_Armor_F_Aegis_APC_Wheeled_04",
"A3_Aegis_Static_F_Aegis_Radar_System_02",
"A3_Aegis_Air_F_Aegis_Heli_Attack_01",
"A3_Aegis_Static_F_Aegis_HMG_01",
"A3_Aegis_Air_F_Aegis_Heli_Attack_04",
"A3_Aegis_Soft_F_Aegis_MRAP_03",
"A3_Aegis_Static_F_Aegis_RF_CommandoMortar",
"A3_Aegis_Armor_F_Aegis_MBT_04",
"A3_Aegis_Armor_F_Aegis_AFV_Wheeled_01",
"A3_Aegis_Armor_F_Aegis_APC_Tracked_01",
"A3_Aegis_Soft_F_Aegis_Truck_01",
"A3_Aegis_Soft_F_Aegis_Quadbike_01",
"A3_Aegis_Soft_F_Aegis_MRAP_02",
"A3_Aegis_Soft_F_Aegis_UGV_01",
"A3_Aegis_Air_F_Aegis_UAV_05",
"A3_Aegis_Static_F_Aegis_Mortar_01",
"A3_Aegis_Armor_F_Aegis_APC_Tracked_02",
"A3_Aegis_Soft_F_Aegis_Hatchback_01",
"A3_Aegis_Air_F_Aegis_UAV_07",
"A3_Aegis_Air_F_Aegis_UAV_06",
"A3_Aegis_Static_F_Aegis_Designator_02",
"A3_Aegis_Armor_F_Aegis_MBT_02",
"A3_Aegis_Static_F_Aegis_RF_TwinMortar",
"A3_Aegis_Soft_F_Aegis_SUV_01",
"A3_Aegis_Soft_F_Aegis_LSV_02",
"A3_Aegis_Air_F_Aegis_Plane_Civil_01",
"A3_Aegis_Static_F_Aegis_GMG_01"
        };
        skipWhenMissingDependencies = 1;
        author = "Synixe Contractors";
        addonRootClass = "A3_Data_F";
        VERSION_CONFIG;
    };
};
#include "CfgVehicles.hpp"
#include "CfgGroups.hpp"
