// Auto-generated file. Do not edit.

class CfgVehicles {
class O_G_Soldier_F;
class Pickup_repair_ig_base_rf;
class B_soldier_LAT2_F;
class I_E_Support_Mort_F;
class O_Soldier_GL_F;
class O_medic_F;
class O_G_Soldier_SL_F;
class Heli_light_03_dynamicLoadout_base_F;
class Helicopter_Base_H;
class O_Truck_03_transport_F;
class TwinMortar_base_RF;
class C_man_pilot_F;
class B_Sharpshooter_F;
class Pickup_fuel_base_rf;
class Pickup_01_rcws_base_rf;
class B_Soldier_GL_F;
class Pickup_covered_base_rf;
class B_D_CTRG_Soldier_M_lxWS;
class I_G_Soldier_SL_F;
class I_Soldier_LAT2_F;
class I_E_Soldier_LAT_F;
class C_man_w_worker_F;
class Pickup_comms_base_rf;
class O_G_Soldier_LAT2_F;
class B_medic_F;
class Pickup_01_Rocket_base_rf;
class B_soldier_repair_F;
class UAV_01_base_F;
class Pickup_01_mmg_base_rf;
class Offroad_01_unarmed_base_F;
class B_G_Soldier_LAT2_F;
class B_Truck_01_fuel_F;
class CommandoMortar_base_RF;
class O_soldier_UAV_F;
class O_soldier_M_F;
class B_G_Soldier_F;
class B_soldier_UAV_F;
class O_A_soldier_F;
class B_ION_soldier_LAT2_lxWS;
class O_Soldier_SL_F;
class B_soldier_AR_F;
class O_Truck_03_fuel_F;
class O_Soldier_HAT_F;
class B_G_Soldier_SL_F;
class Pickup_01_aat_base_rf;
class O_Soldier_AR_F;
class B_Helipilot_F;
class B_GEN_Soldier_F;
class Steerable_Parachute_F;
class Pickup_01_mrl_base_rf;
class B_D_CTRG_Soldier_LAT2_lxWS;
class B_UN_soldier_LAT2_lxWS;
class B_Soldier_SL_F;
class B_Soldier_F;
class O_Soldier_F;
class I_support_AMort_F;
class B_D_CTRG_Soldier_Exp_lxWS;
class O_support_AMort_F;
class Pickup_01_base_rf;
class Helicopter_Base_F;
class Pickup_repair_base_rf;
class C_IDAP_Pilot_01_F;
class B_support_AMort_F;
class Heli_light_03_unarmed_base_F;
class I_G_Soldier_LAT2_F;
class B_ION_Helipilot_lxWS;
class Pickup_01_hmg_base_rf;
class I_G_Soldier_F;

class B_support_CMort_RF: B_support_AMort_F { scope = 1; scopeCurator = 1; };
class B_soldier_repair_RF: B_soldier_repair_F { scope = 1; scopeCurator = 1; };
class B_QRF_Soldier_SL_RF: B_Soldier_SL_F { scope = 1; scopeCurator = 1; };
class B_QRF_Soldier_RF: B_Soldier_F { scope = 1; scopeCurator = 1; };
class B_QRF_Soldier_GL_RF: B_Soldier_GL_F { scope = 1; scopeCurator = 1; };
class B_QRF_medic_RF: B_medic_F { scope = 1; scopeCurator = 1; };
class B_QRF_Soldier_AR_RF: B_soldier_AR_F { scope = 1; scopeCurator = 1; };
class B_QRF_Sharpshooter_RF: B_Sharpshooter_F { scope = 1; scopeCurator = 1; };
class B_QRF_soldier_UAV_RF: B_soldier_UAV_F { scope = 1; scopeCurator = 1; };
class B_QRF_soldier_LAT_RF: B_soldier_LAT2_F { scope = 1; scopeCurator = 1; };
class B_QRF_soldier_LAT2_RF: B_soldier_LAT2_F { scope = 1; scopeCurator = 1; };
class C_Helipilot_Rescue_UniformHolder_RF: B_Helipilot_F { scope = 1; scopeCurator = 1; };
class C_Helipilot_Black_UniformHolder_RF: C_Helipilot_Rescue_UniformHolder_RF { scope = 1; scopeCurator = 1; };
class C_Helipilot_Yellow_UniformHolder_RF: C_Helipilot_Rescue_UniformHolder_RF { scope = 1; scopeCurator = 1; };
class C_Helipilot_Blue_UniformHolder_RF: C_Helipilot_Rescue_UniformHolder_RF { scope = 1; scopeCurator = 1; };
class C_Helipilot_Green_UniformHolder_RF: C_Helipilot_Rescue_UniformHolder_RF { scope = 1; scopeCurator = 1; };
class B_Helipilot_Green_UniformHolder_RF: C_Helipilot_Green_UniformHolder_RF { scope = 1; scopeCurator = 1; };
class B_Helipilot_MTP_UniformHolder_RF: B_Helipilot_F { scope = 1; scopeCurator = 1; };
class C_PilotJacket_black_UniformHolder_RF: C_Helipilot_Rescue_UniformHolder_RF { scope = 1; scopeCurator = 1; };
class C_PilotJacket_brown_UniformHolder_RF: C_PilotJacket_black_UniformHolder_RF { scope = 1; scopeCurator = 1; };
class C_PilotJacket_lbrown_UniformHolder_RF: C_PilotJacket_black_UniformHolder_RF { scope = 1; scopeCurator = 1; };
class C_PilotJacket_Open_black_UniformHolder_RF: C_PilotJacket_black_UniformHolder_RF { scope = 1; scopeCurator = 1; };
class C_PilotJacket_Open_brown_UniformHolder_RF: C_PilotJacket_brown_UniformHolder_RF { scope = 1; scopeCurator = 1; };
class C_PilotJacket_Open_lbrown_UniformHolder_RF: C_PilotJacket_lbrown_UniformHolder_RF { scope = 1; scopeCurator = 1; };
class C_FirefighterFatigues_UniformHolder_RF: C_Helipilot_Rescue_UniformHolder_RF { scope = 1; scopeCurator = 1; };
class C_FirefighterFatigues_RolledUp_UniformHolder_RF: C_FirefighterFatigues_UniformHolder_RF { scope = 1; scopeCurator = 1; };
class B_CommandoMortar_RF: CommandoMortar_base_RF { scope = 1; scopeCurator = 1; };
class B_Pickup_rf: Pickup_01_base_rf { scope = 1; scopeCurator = 1; };
class B_Pickup_Comms_rf: Pickup_comms_base_rf { scope = 1; scopeCurator = 1; };
class B_Pickup_mmg_rf: Pickup_01_mmg_base_rf { scope = 1; scopeCurator = 1; };
class B_Pickup_aat_rf: Pickup_01_aat_base_rf { scope = 1; scopeCurator = 1; };
class B_TwinMortar_RF: TwinMortar_base_RF { scope = 1; scopeCurator = 1; };
class O_support_CMort_RF: O_support_AMort_F { scope = 1; scopeCurator = 1; };
class O_QRF_Soldier_SL_RF: O_Soldier_SL_F { scope = 1; scopeCurator = 1; };
class O_QRF_Soldier_RF: O_Soldier_F { scope = 1; scopeCurator = 1; };
class O_QRF_Soldier_GL_RF: O_Soldier_GL_F { scope = 1; scopeCurator = 1; };
class O_QRF_medic_RF: O_medic_F { scope = 1; scopeCurator = 1; };
class O_QRF_Soldier_AR_RF: O_Soldier_AR_F { scope = 1; scopeCurator = 1; };
class O_QRF_soldier_M_RF: O_soldier_M_F { scope = 1; scopeCurator = 1; };
class O_QRF_Soldier_UAV_RF: O_soldier_UAV_F { scope = 1; scopeCurator = 1; };
class O_QRF_Soldier_HAT_RF: O_Soldier_HAT_F { scope = 1; scopeCurator = 1; };
class O_Truck_03_cargo_RF: O_Truck_03_transport_F { scope = 1; scopeCurator = 1; };
class O_CommandoMortar_RF: B_CommandoMortar_RF { scope = 1; scopeCurator = 1; };
class O_Pickup_rf: Pickup_01_base_rf { scope = 1; scopeCurator = 1; };
class O_Pickup_Comms_rf: Pickup_comms_base_rf { scope = 1; scopeCurator = 1; };
class O_Pickup_rcws_rf: Pickup_01_rcws_base_rf { scope = 1; scopeCurator = 1; };
class O_TwinMortar_RF: TwinMortar_base_RF { scope = 1; scopeCurator = 1; };
class I_support_CMort_RF: I_support_AMort_F { scope = 1; scopeCurator = 1; };
class I_Soldier_LAT_RF: I_Soldier_LAT2_F { scope = 1; scopeCurator = 1; };
class I_CommandoMortar_RF: B_CommandoMortar_RF { scope = 1; scopeCurator = 1; };
class I_Pickup_rf: Pickup_01_base_rf { scope = 1; scopeCurator = 1; };
class I_Pickup_Comms_rf: Pickup_comms_base_rf { scope = 1; scopeCurator = 1; };
class I_Pickup_aat_rf: Pickup_01_aat_base_rf { scope = 1; scopeCurator = 1; };
class I_Pickup_mmg_rf: Pickup_01_mmg_base_rf { scope = 1; scopeCurator = 1; };
class I_Pickup_hmg_rf: Pickup_01_hmg_base_rf { scope = 1; scopeCurator = 1; };
class I_Pickup_rcws_rf: Pickup_01_rcws_base_rf { scope = 1; scopeCurator = 1; };
class I_TwinMortar_RF: TwinMortar_base_RF { scope = 1; scopeCurator = 1; };
class I_G_Scout_RF: I_G_Soldier_SL_F { scope = 1; scopeCurator = 1; };
class I_G_support_CMort_RF: I_G_Soldier_F { scope = 1; scopeCurator = 1; };
class I_G_Soldier_LAT_RF: I_G_Soldier_LAT2_F { scope = 1; scopeCurator = 1; };
class I_G_CommandoMortar_RF: I_CommandoMortar_RF { scope = 1; scopeCurator = 1; };
class C_pilot_story_RF: C_man_pilot_F { scope = 1; scopeCurator = 1; };
class C_pilot2_story_RF: C_man_pilot_F { scope = 1; scopeCurator = 1; };
class C_pilot_RF: C_man_pilot_F { scope = 1; scopeCurator = 1; };
class C_pilot_rescue_RF: C_man_pilot_F { scope = 1; scopeCurator = 1; };
class C_man_firefighter_RF: C_man_w_worker_F { scope = 1; scopeCurator = 1; };
class C_Truck_01_water_rf: B_Truck_01_fuel_F { scope = 1; scopeCurator = 1; };
class C_Truck_01_FFT_rf: C_Truck_01_water_rf { scope = 1; scopeCurator = 1; };
class C_Truck_03_water_rf: O_Truck_03_fuel_F { scope = 1; scopeCurator = 1; };
class Pickup_01_Outside_Cargo_rf: Offroad_01_unarmed_base_F { scope = 1; scopeCurator = 1; };
class Pickup_01_Outside_Cargo1_rf: Pickup_01_Outside_Cargo_rf { scope = 1; scopeCurator = 1; };
class Pickup_01_Outside_Cargo2_rf: Pickup_01_Outside_Cargo1_rf { scope = 1; scopeCurator = 1; };
class Pickup_01_Outside_Cargo3_rf: Pickup_01_Outside_Cargo1_rf { scope = 1; scopeCurator = 1; };
class Pickup_01_Outside_Cargo4_rf: Pickup_01_Outside_Cargo1_rf { scope = 1; scopeCurator = 1; };
class C_Pickup_rf: Pickup_01_base_rf { scope = 1; scopeCurator = 1; };
class C_Pickup_repair_rf: Pickup_repair_base_rf { scope = 1; scopeCurator = 1; };
class C_Pickup_covered_rf: Pickup_covered_base_rf { scope = 1; scopeCurator = 1; };
class fake_searchlight_RF: UAV_01_base_F { scope = 1; scopeCurator = 1; };
class fake_searchlight_IR_RF: fake_searchlight_RF { scope = 1; scopeCurator = 1; };
class Heli_EC_01_base_RF: Helicopter_Base_H { scope = 1; scopeCurator = 1; };
class Heli_EC_01_civ_base_RF: Heli_EC_01_base_RF { scope = 1; scopeCurator = 1; };
class Heli_EC_01A_base_RF: Heli_EC_01_base_RF { scope = 1; scopeCurator = 1; };
class Heli_EC_01A_civ_base_RF: Heli_EC_01A_base_RF { scope = 1; scopeCurator = 1; };
class Heli_EC_01A_military_base_RF: Heli_EC_01A_base_RF { scope = 1; scopeCurator = 1; };
class Heli_EC_02_base_RF: Heli_EC_01_base_RF { scope = 1; scopeCurator = 1; };
class Heli_EC_03_base_RF: Heli_EC_01_base_RF { scope = 1; scopeCurator = 1; };
class Heli_EC_04_base_RF: Heli_EC_01_base_RF { scope = 1; scopeCurator = 1; };
class Heli_EC_04_rescue_base_RF: Heli_EC_04_base_RF { scope = 1; scopeCurator = 1; };
class Heli_EC_04_military_base_RF: Heli_EC_04_base_RF { scope = 1; scopeCurator = 1; };
class C_Heli_EC_04_rescue_RF: Heli_EC_04_rescue_base_RF { scope = 1; scopeCurator = 1; };
class C_Heli_EC_01_civ_RF: Heli_EC_01_civ_base_RF { scope = 1; scopeCurator = 1; };
class C_Heli_EC_01A_civ_RF: Heli_EC_01A_civ_base_RF { scope = 1; scopeCurator = 1; };
class UAV_RC40_Base_RF: Helicopter_Base_F { scope = 1; scopeCurator = 1; };
class UAV_RC40_Base_Sensor_RF: UAV_RC40_Base_RF { scope = 1; scopeCurator = 1; };
class UAV_RC40_Base_HE_RF: UAV_RC40_Base_RF { scope = 1; scopeCurator = 1; };
class UAV_RC40_Base_SmokeWhite_RF: UAV_RC40_Base_HE_RF { scope = 1; scopeCurator = 1; };
class UAV_RC40_Base_SmokeBlue_RF: UAV_RC40_Base_HE_RF { scope = 1; scopeCurator = 1; };
class UAV_RC40_Base_SmokeRed_RF: UAV_RC40_Base_HE_RF { scope = 1; scopeCurator = 1; };
class UAV_RC40_Base_SmokeGreen_RF: UAV_RC40_Base_HE_RF { scope = 1; scopeCurator = 1; };
class UAV_RC40_Base_SmokeOrange_RF: UAV_RC40_Base_HE_RF { scope = 1; scopeCurator = 1; };
class C_UAV_RC40_SENSOR_RF: UAV_RC40_Base_Sensor_RF { scope = 1; scopeCurator = 1; };
class C_UAV_RC40_HE_RF: UAV_RC40_Base_HE_RF { scope = 1; scopeCurator = 1; };
class C_UAV_RC40_SmokeWhite_RF: UAV_RC40_Base_SmokeWhite_RF { scope = 1; scopeCurator = 1; };
class C_UAV_RC40_SmokeBlue_RF: UAV_RC40_Base_SmokeBlue_RF { scope = 1; scopeCurator = 1; };
class C_UAV_RC40_SmokeRed_RF: UAV_RC40_Base_SmokeRed_RF { scope = 1; scopeCurator = 1; };
class C_UAV_RC40_SmokeGreen_RF: UAV_RC40_Base_SmokeGreen_RF { scope = 1; scopeCurator = 1; };
class C_UAV_RC40_SmokeOrange_RF: UAV_RC40_Base_SmokeOrange_RF { scope = 1; scopeCurator = 1; };
class B_G_Scout_RF: B_G_Soldier_SL_F { scope = 1; scopeCurator = 1; };
class B_G_support_CMort_RF: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class B_G_Soldier_LAT_RF: B_G_Soldier_LAT2_F { scope = 1; scopeCurator = 1; };
class B_G_CommandoMortar_RF: B_CommandoMortar_RF { scope = 1; scopeCurator = 1; };
class B_G_Pickup_rf: Pickup_01_base_rf { scope = 1; scopeCurator = 1; };
class B_G_Pickup_mmg_rf: Pickup_01_mmg_base_rf { scope = 1; scopeCurator = 1; };
class B_G_Pickup_hmg_rf: Pickup_01_hmg_base_rf { scope = 1; scopeCurator = 1; };
class B_G_Pickup_mrl_rf: Pickup_01_mrl_base_rf { scope = 1; scopeCurator = 1; };
class B_G_Pickup_aat_rf: Pickup_01_aat_base_rf { scope = 1; scopeCurator = 1; };
class B_G_Pickup_fuel_rf: Pickup_fuel_base_rf { scope = 1; scopeCurator = 1; };
class B_G_Pickup_repair_rf: Pickup_repair_ig_base_rf { scope = 1; scopeCurator = 1; };
class B_G_Pickup_Rocket_rf: Pickup_01_Rocket_base_rf { scope = 1; scopeCurator = 1; };
class O_G_Scout_RF: O_G_Soldier_SL_F { scope = 1; scopeCurator = 1; };
class O_G_support_CMort_RF: O_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_G_Soldier_LAT_RF: O_G_Soldier_LAT2_F { scope = 1; scopeCurator = 1; };
class O_G_CommandoMortar_RF: O_CommandoMortar_RF { scope = 1; scopeCurator = 1; };
class O_G_Pickup_rf: B_G_Pickup_rf { scope = 1; scopeCurator = 1; };
class O_G_Pickup_mmg_rf: B_G_Pickup_mmg_rf { scope = 1; scopeCurator = 1; };
class O_G_Pickup_hmg_rf: B_G_Pickup_hmg_rf { scope = 1; scopeCurator = 1; };
class O_G_Pickup_mrl_rf: B_G_Pickup_mrl_rf { scope = 1; scopeCurator = 1; };
class O_G_Pickup_aat_rf: B_G_Pickup_aat_rf { scope = 1; scopeCurator = 1; };
class O_G_Pickup_fuel_rf: B_G_Pickup_fuel_rf { scope = 1; scopeCurator = 1; };
class O_G_Pickup_repair_rf: B_G_Pickup_repair_rf { scope = 1; scopeCurator = 1; };
class O_G_Pickup_Rocket_rf: B_G_Pickup_Rocket_rf { scope = 1; scopeCurator = 1; };
class I_C_Pickup_rf: Pickup_01_base_rf { scope = 1; scopeCurator = 1; };
class I_C_Pickup_mmg_rf: Pickup_01_mmg_base_rf { scope = 1; scopeCurator = 1; };
class I_C_Pickup_hmg_rf: Pickup_01_hmg_base_rf { scope = 1; scopeCurator = 1; };
class I_C_Pickup_mrl_rf: Pickup_01_mrl_base_rf { scope = 1; scopeCurator = 1; };
class B_T_Truck_01_FFT_rf: C_Truck_01_FFT_rf { scope = 1; scopeCurator = 1; };
class B_T_Pickup_rf: B_Pickup_rf { scope = 1; scopeCurator = 1; };
class B_T_Pickup_Comms_rf: B_Pickup_Comms_rf { scope = 1; scopeCurator = 1; };
class B_T_Pickup_mmg_rf: B_Pickup_mmg_rf { scope = 1; scopeCurator = 1; };
class B_T_Pickup_aat_rf: B_Pickup_aat_rf { scope = 1; scopeCurator = 1; };
class B_T_TwinMortar_RF: B_TwinMortar_RF { scope = 1; scopeCurator = 1; };
class B_D_CTRG_CommandoMortar_RF: B_CommandoMortar_RF { scope = 1; scopeCurator = 1; };
class B_GEN_Helipilot_RF: B_Helipilot_F { scope = 1; scopeCurator = 1; };
class B_GEN_Pickup_covered_rf: Pickup_covered_base_rf { scope = 1; scopeCurator = 1; };
class B_GEN_Heli_EC_01_RF: Heli_EC_01_base_RF { scope = 1; scopeCurator = 1; };
class O_T_Truck_03_cargo_RF: O_Truck_03_cargo_RF { scope = 1; scopeCurator = 1; };
class O_T_Pickup_rf: O_Pickup_rf { scope = 1; scopeCurator = 1; };
class O_T_Pickup_Comms_rf: O_Pickup_Comms_rf { scope = 1; scopeCurator = 1; };
class O_T_Pickup_rcws_rf: O_Pickup_rcws_rf { scope = 1; scopeCurator = 1; };
class O_T_TwinMortar_RF: O_TwinMortar_RF { scope = 1; scopeCurator = 1; };
class C_IDAP_Pickup_rf: Pickup_01_base_rf { scope = 1; scopeCurator = 1; };
class C_IDAP_Pickup_fuel_rf: Pickup_fuel_base_rf { scope = 1; scopeCurator = 1; };
class C_IDAP_Pickup_covered_rf: Pickup_covered_base_rf { scope = 1; scopeCurator = 1; };
class C_IDAP_Pickup_water_rf: C_IDAP_Pickup_rf { scope = 1; scopeCurator = 1; };
class C_IDAP_Heli_EC_01A_civ_RF: Heli_EC_01A_civ_base_RF { scope = 1; scopeCurator = 1; };
class I_E_CommandoMortar_RF: I_CommandoMortar_RF { scope = 1; scopeCurator = 1; };
class I_E_Pickup_rf: Pickup_01_base_rf { scope = 1; scopeCurator = 1; };
class I_E_Pickup_Comms_rf: Pickup_comms_base_rf { scope = 1; scopeCurator = 1; };
class I_E_Pickup_Covered_rf: Pickup_covered_base_rf { scope = 1; scopeCurator = 1; };
class I_E_Pickup_aat_rf: Pickup_01_aat_base_rf { scope = 1; scopeCurator = 1; };
class I_E_EC_02_RF: Heli_EC_02_base_RF { scope = 1; scopeCurator = 1; };
class I_E_Heli_EC_01A_military_RF: Heli_EC_01A_military_base_RF { scope = 1; scopeCurator = 1; };
class B_ION_soldier_LAT_RF: B_ION_soldier_LAT2_lxWS { scope = 1; scopeCurator = 1; };
class B_ION_Pickup_rf: Pickup_01_base_rf { scope = 1; scopeCurator = 1; };
class B_ION_Pickup_mmg_rf: Pickup_01_mmg_base_rf { scope = 1; scopeCurator = 1; };
class B_ION_Pickup_aat_rf: Pickup_01_aat_base_rf { scope = 1; scopeCurator = 1; };
class B_ION_Pickup_rcws_rf: Pickup_01_rcws_base_rf { scope = 1; scopeCurator = 1; };
class B_ION_Helipilot_RF: B_ION_Helipilot_lxWS { scope = 1; scopeCurator = 1; };
class B_ION_Heli_EC_01_RF: Heli_EC_01_base_RF { scope = 1; scopeCurator = 1; };
class B_UN_soldier_LAT_rf: B_UN_soldier_LAT2_lxWS { scope = 1; scopeCurator = 1; };
class B_UN_Pickup_rf: Pickup_01_base_rf { scope = 1; scopeCurator = 1; };
class B_UN_Pickup_mmg_rf: Pickup_01_mmg_base_rf { scope = 1; scopeCurator = 1; };
class B_UN_Heli_EC_01A_military_RF: Heli_EC_01A_military_base_RF { scope = 1; scopeCurator = 1; };
class I_Tura_Pickup_01_RF: Pickup_01_base_rf { scope = 1; scopeCurator = 1; };
class I_Tura_Pickup_01_mmg_rf: Pickup_01_mmg_base_rf { scope = 1; scopeCurator = 1; };
class I_Tura_Pickup_01_hmg_rf: Pickup_01_hmg_base_rf { scope = 1; scopeCurator = 1; };
class I_Tura_Pickup_fuel_rf: Pickup_fuel_base_rf { scope = 1; scopeCurator = 1; };
class I_Tura_Pickup_01_Rocket_rf: Pickup_01_Rocket_base_rf { scope = 1; scopeCurator = 1; };
class B_Tura_Pickup_01_RF: I_Tura_Pickup_01_RF { scope = 1; scopeCurator = 1; };
class B_Tura_Pickup_01_mmg_RF: I_Tura_Pickup_01_mmg_rf { scope = 1; scopeCurator = 1; };
class B_Tura_Pickup_01_hmg_RF: I_Tura_Pickup_01_hmg_rf { scope = 1; scopeCurator = 1; };
class B_Tura_Pickup_01_fuel_RF: I_Tura_Pickup_fuel_rf { scope = 1; scopeCurator = 1; };
class B_Tura_Pickup_01_Rocket_rf: I_Tura_Pickup_01_Rocket_rf { scope = 1; scopeCurator = 1; };
class O_Tura_Pickup_01_RF: I_Tura_Pickup_01_RF { scope = 1; scopeCurator = 1; };
class O_Tura_Pickup_01_mmg_RF: I_Tura_Pickup_01_mmg_rf { scope = 1; scopeCurator = 1; };
class O_Tura_Pickup_01_hmg_RF: I_Tura_Pickup_01_hmg_rf { scope = 1; scopeCurator = 1; };
class O_Tura_Pickup_01_fuel_RF: I_Tura_Pickup_fuel_rf { scope = 1; scopeCurator = 1; };
class O_Tura_Pickup_01_Rocket_rf: I_Tura_Pickup_01_Rocket_rf { scope = 1; scopeCurator = 1; };
class B_Heli_light_03_dynamicLoadout_RF: Heli_light_03_dynamicLoadout_base_F { scope = 1; scopeCurator = 1; };
class B_Heli_light_03_unarmed_RF: Heli_light_03_unarmed_base_F { scope = 1; scopeCurator = 1; };
class B_Truck_01_FFT_rf: C_Truck_01_FFT_rf { scope = 1; scopeCurator = 1; };
class B_Heli_EC_03_RF: Heli_EC_03_base_RF { scope = 1; scopeCurator = 1; };
class B_Heli_EC_04_military_RF: Heli_EC_04_military_base_RF { scope = 1; scopeCurator = 1; };
class B_Heli_EC_02_RF: Heli_EC_02_base_RF { scope = 1; scopeCurator = 1; };
class B_UAV_RC40_SENSOR_RF: UAV_RC40_Base_Sensor_RF { scope = 1; scopeCurator = 1; };
class B_UAV_RC40_HE_RF: UAV_RC40_Base_HE_RF { scope = 1; scopeCurator = 1; };
class B_UAV_RC40_SmokeWhite_RF: UAV_RC40_Base_SmokeWhite_RF { scope = 1; scopeCurator = 1; };
class B_UAV_RC40_SmokeBlue_RF: UAV_RC40_Base_SmokeBlue_RF { scope = 1; scopeCurator = 1; };
class B_UAV_RC40_SmokeRed_RF: UAV_RC40_Base_SmokeRed_RF { scope = 1; scopeCurator = 1; };
class B_UAV_RC40_SmokeGreen_RF: UAV_RC40_Base_SmokeGreen_RF { scope = 1; scopeCurator = 1; };
class B_UAV_RC40_SmokeOrange_RF: UAV_RC40_Base_SmokeOrange_RF { scope = 1; scopeCurator = 1; };
class O_UAV_RC40_SENSOR_RF: UAV_RC40_Base_Sensor_RF { scope = 1; scopeCurator = 1; };
class O_UAV_RC40_HE_RF: UAV_RC40_Base_HE_RF { scope = 1; scopeCurator = 1; };
class O_UAV_RC40_SmokeWhite_RF: UAV_RC40_Base_SmokeWhite_RF { scope = 1; scopeCurator = 1; };
class O_UAV_RC40_SmokeBlue_RF: UAV_RC40_Base_SmokeBlue_RF { scope = 1; scopeCurator = 1; };
class O_UAV_RC40_SmokeRed_RF: UAV_RC40_Base_SmokeRed_RF { scope = 1; scopeCurator = 1; };
class O_UAV_RC40_SmokeGreen_RF: UAV_RC40_Base_SmokeGreen_RF { scope = 1; scopeCurator = 1; };
class O_UAV_RC40_SmokeOrange_RF: UAV_RC40_Base_SmokeOrange_RF { scope = 1; scopeCurator = 1; };
class I_Heli_light_03_dynamicLoadout_RF: B_Heli_light_03_dynamicLoadout_RF { scope = 1; scopeCurator = 1; };
class I_Heli_light_03_unarmed_RF: B_Heli_light_03_unarmed_RF { scope = 1; scopeCurator = 1; };
class I_Heli_EC_02_RF: Heli_EC_02_base_RF { scope = 1; scopeCurator = 1; };
class I_Heli_EC_01A_military_RF: Heli_EC_01A_military_base_RF { scope = 1; scopeCurator = 1; };
class I_UAV_RC40_SENSOR_RF: UAV_RC40_Base_Sensor_RF { scope = 1; scopeCurator = 1; };
class I_UAV_RC40_HE_RF: UAV_RC40_Base_HE_RF { scope = 1; scopeCurator = 1; };
class I_UAV_RC40_SmokeWhite_RF: UAV_RC40_Base_SmokeWhite_RF { scope = 1; scopeCurator = 1; };
class I_UAV_RC40_SmokeBlue_RF: UAV_RC40_Base_SmokeBlue_RF { scope = 1; scopeCurator = 1; };
class I_UAV_RC40_SmokeRed_RF: UAV_RC40_Base_SmokeRed_RF { scope = 1; scopeCurator = 1; };
class I_UAV_RC40_SmokeGreen_RF: UAV_RC40_Base_SmokeGreen_RF { scope = 1; scopeCurator = 1; };
class I_UAV_RC40_SmokeOrange_RF: UAV_RC40_Base_SmokeOrange_RF { scope = 1; scopeCurator = 1; };
class I_G_Pickup_rf: B_G_Pickup_rf { scope = 1; scopeCurator = 1; };
class I_G_Pickup_mmg_rf: B_G_Pickup_mmg_rf { scope = 1; scopeCurator = 1; };
class I_G_Pickup_hmg_rf: B_G_Pickup_hmg_rf { scope = 1; scopeCurator = 1; };
class I_G_Pickup_mrl_rf: B_G_Pickup_mrl_rf { scope = 1; scopeCurator = 1; };
class I_G_Pickup_aat_rf: B_G_Pickup_aat_rf { scope = 1; scopeCurator = 1; };
class I_G_Pickup_fuel_rf: B_G_Pickup_fuel_rf { scope = 1; scopeCurator = 1; };
class I_G_Pickup_repair_rf: B_G_Pickup_repair_rf { scope = 1; scopeCurator = 1; };
class I_G_Pickup_Rocket_rf: B_G_Pickup_Rocket_rf { scope = 1; scopeCurator = 1; };
class Steerable_Parachute_Orange_RF: Steerable_Parachute_F { scope = 1; scopeCurator = 1; };
class Steerable_Parachute_White_RF: Steerable_Parachute_Orange_RF { scope = 1; scopeCurator = 1; };
class Steerable_Parachute_Green_RF: Steerable_Parachute_Orange_RF { scope = 1; scopeCurator = 1; };
class Steerable_Parachute_Blue_RF: Steerable_Parachute_Orange_RF { scope = 1; scopeCurator = 1; };
class Steerable_Parachute_Yellow_RF: Steerable_Parachute_Orange_RF { scope = 1; scopeCurator = 1; };
class B_D_CTRG_support_CMort_RF: B_D_CTRG_Soldier_Exp_lxWS { scope = 1; scopeCurator = 1; };
class B_D_CTRG_Soldier_LAT_RF: B_D_CTRG_Soldier_LAT2_lxWS { scope = 1; scopeCurator = 1; };
class B_GEN_Soldier_RF: B_GEN_Soldier_F { scope = 1; scopeCurator = 1; };
class C_IDAP_Pilot_RF: C_IDAP_Pilot_01_F { scope = 1; scopeCurator = 1; };
class I_E_support_CMort_RF: I_E_Support_Mort_F { scope = 1; scopeCurator = 1; };
class I_E_Soldier_LAT_RF: I_E_Soldier_LAT_F { scope = 1; scopeCurator = 1; };
class I_E_Heli_light_03_dynamicLoadout_RF: I_Heli_light_03_dynamicLoadout_RF { scope = 1; scopeCurator = 1; };
class I_E_Heli_light_03_unarmed_RF: I_Heli_light_03_unarmed_RF { scope = 1; scopeCurator = 1; };
class I_SFIA_Heli_EC_02_RF: I_Heli_EC_02_RF { scope = 1; scopeCurator = 1; };
class O_SFIA_Heli_EC_02_RF: I_SFIA_Heli_EC_02_RF { scope = 1; scopeCurator = 1; };
class O_A_scout_RF: O_A_soldier_F { scope = 1; scopeCurator = 1; };
class B_D_CTRG_Sharpshooter_lxWS: B_D_CTRG_Soldier_M_lxWS { scope = 1; scopeCurator = 1; };
};
