// Auto-generated file. Do not edit.

class CfgVehicles {
class B_APC_Tracked_01_rcws_F;
class B_Boat_Armed_01_minigun_F;
class B_G_Offroad_01_repair_F;
class B_G_Soldier_F;
class B_Heli_Light_01_F;
class B_Heli_Light_01_armed_F;
class B_Protagonist_VR_F;
class B_Soldier_F;
class B_Soldier_SL_F;
class B_Soldier_base_F;
class B_Soldier_diver_base_F;
class B_diver_F;
class B_soldier_AR_F;
class Boat_Transport_02_base_F;
class C_Heli_Light_01_civil_F;
class C_Man_casual_1_F;
class C_Offroad_01_F;
class C_Quadbike_01_F;
class C_SUV_01_F;
class C_Truck_02_box_F;
class C_Truck_02_covered_F;
class C_Truck_02_fuel_F;
class C_Truck_02_transport_F;
class C_Van_01_transport_F;
class C_Van_02_transport_F;
class C_Van_02_vehicle_F;
class C_man_1;
class C_man_pilot_F;
class C_man_w_worker_F;
class I_APC_Wheeled_03_cannon_F;
class I_C_Offroad_02_AT_F;
class I_C_Offroad_02_LMG_F;
class I_C_Offroad_02_unarmed_F;
class I_G_HMG_02_F;
class I_G_HMG_02_high_F;
class I_G_Mortar_01_F;
class I_G_Offroad_01_F;
class I_G_Offroad_01_armed_F;
class I_Heli_Transport_02_F;
class I_Soldier_02_F;
class I_diver_F;
class I_soldier_F;
class MRAP_03_base_F;
class MRAP_03_gmg_base_F;
class MRAP_03_hmg_base_F;
class O_APC_Wheeled_02_rcws_v2_F;
class O_G_Boat_Transport_01_F;
class O_G_HMG_02_F;
class O_G_HMG_02_high_F;
class O_G_Mortar_01_F;
class O_G_Offroad_01_AT_F;
class O_G_Offroad_01_F;
class O_G_Offroad_01_repair_F;
class O_G_Quadbike_01_F;
class O_G_Van_01_fuel_F;
class O_G_Van_01_transport_F;
class O_G_Van_02_transport_F;
class O_G_Van_02_vehicle_F;
class O_HMG_01_F;
class O_HMG_01_high_F;
class O_Heli_Light_02_F;
class O_Heli_Light_02_unarmed_F;
class O_Soldier_F;
class O_Soldier_diver_base_F;
class O_Truck_02_Ammo_F;
class O_Truck_02_box_F;
class O_Truck_02_covered_F;
class O_Truck_02_fuel_F;
class O_Truck_02_medical_F;
class O_Truck_02_transport_F;
class O_diver_F;
class O_static_AT_F;
class Offroad_01_military_comms_base_F;
class Offroad_01_military_covered_base_F;
class Offroad_01_repair_military_base_F;
class Offroad_02_AT_base_F;
class Offroad_02_LMG_base_F;
class Offroad_02_unarmed_base_F;
class Plane_Civil_01_base_F;
class Van_02_transport_base_F;
class Van_02_vehicle_base_F;

class B_MU_CTRG_base_F: B_Soldier_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_R_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_SL_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_TL_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_lite_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_GL_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_AR_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_M_Mk18_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_M_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_LAT_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_medic_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_officer_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_A_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_AAR_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_repair_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_exp_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_AT_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_AA_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_engineer_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_AAT_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_AAA_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_sniper_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_spotter_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_UAVOP_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_helipilot_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_MG_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CTRG_AMG_F: B_MU_CTRG_base_F { scope = 1; scopeCurator = 1; };
class MU_CTRG_speedboat: B_Boat_Armed_01_minigun_F { scope = 1; scopeCurator = 1; };
class B_MU_CDT_diver_base_F: B_Soldier_diver_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CDT_diver_TL_F: B_MU_CDT_diver_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CDT_diver_F: B_MU_CDT_diver_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CDT_diver_medic_F: B_MU_CDT_diver_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CDT_diver_exp_F: B_MU_CDT_diver_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CDT_diver_AR_F: B_MU_CDT_diver_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CDT_diver_M_F: B_MU_CDT_diver_base_F { scope = 1; scopeCurator = 1; };
class B_MU_CDT_diver_A_F: B_MU_CDT_diver_base_F { scope = 1; scopeCurator = 1; };
class B_MU_DD_diver_medic_F: B_diver_F { scope = 1; scopeCurator = 1; };
class B_MU_SF_base_F: B_Soldier_F { scope = 1; scopeCurator = 1; };
class B_MU_SF_TL_F: B_MU_SF_base_F { scope = 1; scopeCurator = 1; };
class B_MU_SF_JTAC_F: B_MU_SF_base_F { scope = 1; scopeCurator = 1; };
class B_MU_SF_medic_F: B_MU_SF_base_F { scope = 1; scopeCurator = 1; };
class B_MU_SF_AR_F: B_MU_SF_base_F { scope = 1; scopeCurator = 1; };
class B_MU_SF_M_F: B_MU_SF_base_F { scope = 1; scopeCurator = 1; };
class B_MU_SF_engineer_F: B_MU_SF_base_F { scope = 1; scopeCurator = 1; };
class B_MU_SF_AT_F: B_MU_SF_base_F { scope = 1; scopeCurator = 1; };
class B_MU_SF_sniper_F: B_MU_SF_base_F { scope = 1; scopeCurator = 1; };
class MU_NATO_Strider: MRAP_03_base_F { scope = 1; scopeCurator = 1; };
class MU_NATO_Strider_HMG: MRAP_03_hmg_base_F { scope = 1; scopeCurator = 1; };
class MU_NATO_Strider_GMG: MRAP_03_gmg_base_F { scope = 1; scopeCurator = 1; };
class MU_NATO_Panther_unarmed: B_APC_Tracked_01_rcws_F { scope = 1; scopeCurator = 1; };
class B_MU_soldier_sage_base: B_Soldier_F { scope = 1; scopeCurator = 1; };
class B_MU_soldier_sage_vest_base: B_Soldier_SL_F { scope = 1; scopeCurator = 1; };
class B_MU_soldier_sage_tshirt_base: B_soldier_AR_F { scope = 1; scopeCurator = 1; };
class B_MU_soldier_wdl_base: B_Soldier_F { scope = 1; scopeCurator = 1; };
class B_MU_soldier_wdl_vest_base: B_Soldier_SL_F { scope = 1; scopeCurator = 1; };
class B_MU_soldier_wdl_tshirt_base: B_soldier_AR_F { scope = 1; scopeCurator = 1; };
class B_MU_soldier_gen_base: B_Soldier_F { scope = 1; scopeCurator = 1; };
class B_MU_soldier_gen_vest_base: B_Soldier_SL_F { scope = 1; scopeCurator = 1; };
class B_MU_soldier_gen_tshirt_base: B_soldier_AR_F { scope = 1; scopeCurator = 1; };
class B_MU_Protagonist_VR_nolight_base: B_Protagonist_VR_F { scope = 1; scopeCurator = 1; };
class O_MU_CDT_diver_base_F: O_Soldier_diver_base_F { scope = 1; scopeCurator = 1; };
class O_MU_CDT_diver_TL_F: O_MU_CDT_diver_base_F { scope = 1; scopeCurator = 1; };
class O_MU_CDT_diver_F: O_MU_CDT_diver_base_F { scope = 1; scopeCurator = 1; };
class O_MU_CDT_diver_medic_F: O_MU_CDT_diver_base_F { scope = 1; scopeCurator = 1; };
class O_MU_CDT_diver_exp_F: O_MU_CDT_diver_base_F { scope = 1; scopeCurator = 1; };
class O_MU_CDT_diver_AR_F: O_MU_CDT_diver_base_F { scope = 1; scopeCurator = 1; };
class O_MU_CDT_diver_M_F: O_MU_CDT_diver_base_F { scope = 1; scopeCurator = 1; };
class O_MU_CDT_diver_A_F: O_MU_CDT_diver_base_F { scope = 1; scopeCurator = 1; };
class O_MU_DD_diver_medic_F: O_diver_F { scope = 1; scopeCurator = 1; };
class MU_CSAT_Marid_unarmed: O_APC_Wheeled_02_rcws_v2_F { scope = 1; scopeCurator = 1; };
class O_MU_CombatUniform_RUcamo_base: O_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_RUSP_base_F: O_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_RUSP_R_F: O_MU_RUSP_base_F { scope = 1; scopeCurator = 1; };
class O_MU_RUSP_RN_F: O_MU_RUSP_base_F { scope = 1; scopeCurator = 1; };
class O_MU_RUSP_TL_F: O_MU_RUSP_base_F { scope = 1; scopeCurator = 1; };
class O_MU_RUSP_GL_F: O_MU_RUSP_base_F { scope = 1; scopeCurator = 1; };
class O_MU_RUSP_medic_F: O_MU_RUSP_base_F { scope = 1; scopeCurator = 1; };
class O_MU_RUSP_engineer_F: O_MU_RUSP_base_F { scope = 1; scopeCurator = 1; };
class O_MU_RUSP_sniper_F: O_MU_RUSP_base_F { scope = 1; scopeCurator = 1; };
class O_MU_RUSP_AT_F: O_MU_RUSP_base_F { scope = 1; scopeCurator = 1; };
class O_MU_RUSP_AR_F: O_MU_RUSP_base_F { scope = 1; scopeCurator = 1; };
class O_MU_RUSP_A_F: O_MU_RUSP_base_F { scope = 1; scopeCurator = 1; };
class O_MU_RUSP_M_F: O_MU_RUSP_base_F { scope = 1; scopeCurator = 1; };
class I_MU_DD_diver_medic_F: I_diver_F { scope = 1; scopeCurator = 1; };
class I_MU_soldier_sand_base: I_soldier_F { scope = 1; scopeCurator = 1; };
class I_MU_soldier_sand_vest_base: I_Soldier_02_F { scope = 1; scopeCurator = 1; };
class I_MU_soldier_para_base: I_soldier_F { scope = 1; scopeCurator = 1; };
class I_MU_soldier_para_vest_base: I_Soldier_02_F { scope = 1; scopeCurator = 1; };
class O_MU_wetsuit_ru_base: I_diver_F { scope = 1; scopeCurator = 1; };
class I_MU_GrDa_base_F: I_soldier_F { scope = 1; scopeCurator = 1; };
class I_MU_GrDa_R_F: I_MU_GrDa_base_F { scope = 1; scopeCurator = 1; };
class I_MU_GrDa_R_ADR_F: I_MU_GrDa_base_F { scope = 1; scopeCurator = 1; };
class I_MU_GrDa_Rtws_F: I_MU_GrDa_base_F { scope = 1; scopeCurator = 1; };
class I_MU_GrDa_TL_F: I_MU_GrDa_base_F { scope = 1; scopeCurator = 1; };
class I_MU_GrDa_GL_F: I_MU_GrDa_base_F { scope = 1; scopeCurator = 1; };
class I_MU_GrDa_M_F: I_MU_GrDa_base_F { scope = 1; scopeCurator = 1; };
class I_MU_GrDa_medic_F: I_MU_GrDa_base_F { scope = 1; scopeCurator = 1; };
class I_MU_GrDa_A_F: I_MU_GrDa_base_F { scope = 1; scopeCurator = 1; };
class I_MU_GrDa_AR_F: I_MU_GrDa_base_F { scope = 1; scopeCurator = 1; };
class I_MU_GrDa_LAT_F: I_MU_GrDa_base_F { scope = 1; scopeCurator = 1; };
class I_MU_GrDa_AT: I_MU_GrDa_LAT_F { scope = 1; scopeCurator = 1; };
class I_MU_GrDa_engineer_F: I_MU_GrDa_base_F { scope = 1; scopeCurator = 1; };
class I_MU_GrDa_sniper_F: I_MU_GrDa_base_F { scope = 1; scopeCurator = 1; };
class C_MU_man_helipilot_F: C_man_pilot_F { scope = 1; scopeCurator = 1; };
class MU_CIV_Zamak_transport_covered: C_Truck_02_covered_F { scope = 1; scopeCurator = 1; };
class MU_CIV_Zamak_fuel: C_Truck_02_fuel_F { scope = 1; scopeCurator = 1; };
class MU_CIV_Zamak_repair: C_Truck_02_box_F { scope = 1; scopeCurator = 1; };
class C_MU_coverall_dirty2_base: C_man_w_worker_F { scope = 1; scopeCurator = 1; };
class C_MU_coverall_black_base: C_man_w_worker_F { scope = 1; scopeCurator = 1; };
class C_MU_coverall_urbancamo_base: C_man_w_worker_F { scope = 1; scopeCurator = 1; };
class C_MU_coverall_grey_base: C_man_w_worker_F { scope = 1; scopeCurator = 1; };
class B_MU_PoloshirtPants1_base: C_Man_casual_1_F { scope = 1; scopeCurator = 1; };
class B_MU_PoloshirtPants2_base: C_Man_casual_1_F { scope = 1; scopeCurator = 1; };
class C_MU_man_police_officer_F: C_man_pilot_F { scope = 1; scopeCurator = 1; };
class MU_CIV_police_Offroad_01_F: C_Offroad_01_F { scope = 1; scopeCurator = 1; };
class C_MU_man_random_civil_F: C_man_1 { scope = 1; scopeCurator = 1; };
class C_MU_man_random_civil_euro_F: C_man_1 { scope = 1; scopeCurator = 1; };
class C_MU_man_random_civil_asia_F: C_man_1 { scope = 1; scopeCurator = 1; };
class C_MU_man_random_civil_afro_F: C_man_1 { scope = 1; scopeCurator = 1; };
class C_MU_man_random_civil_persan_F: C_man_1 { scope = 1; scopeCurator = 1; };
class C_MU_man_random_civil_tanoan_F: C_man_1 { scope = 1; scopeCurator = 1; };
class C_MU_man_persan_F: C_man_1 { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment_grey_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment_grey_base: B_MU_GuerillaGarment_grey_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment_grey_base: B_MU_GuerillaGarment_grey_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment_redcamo_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment_redcamo_base: B_MU_GuerillaGarment_redcamo_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment_redcamo_base: B_MU_GuerillaGarment_redcamo_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment_skull_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment_skull_base: B_MU_GuerillaGarment_skull_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment_skull_base: B_MU_GuerillaGarment_skull_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment_brown_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment_brown_base: B_MU_GuerillaGarment_brown_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment_brown_base: B_MU_GuerillaGarment_brown_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment_orange_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment_orange_base: B_MU_GuerillaGarment_orange_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment_orange_base: B_MU_GuerillaGarment_orange_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment_yellow_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment_yellow_base: B_MU_GuerillaGarment_yellow_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment_yellow_base: B_MU_GuerillaGarment_yellow_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment_blue_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment_blue_base: B_MU_GuerillaGarment_blue_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment_blue_base: B_MU_GuerillaGarment_blue_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment_dirty_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment_dirty_base: B_MU_GuerillaGarment_dirty_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment_dirty_base: B_MU_GuerillaGarment_dirty_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment_green_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment_green_base: B_MU_GuerillaGarment_green_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment_green_base: B_MU_GuerillaGarment_green_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment2_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment2_base: B_MU_GuerillaGarment2_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment2_base: B_MU_GuerillaGarment2_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment2_grey_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment2_grey_base: B_MU_GuerillaGarment2_grey_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment2_grey_base: B_MU_GuerillaGarment2_grey_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment2_redcamo_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment2_redcamo_base: B_MU_GuerillaGarment2_redcamo_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment2_redcamo_base: B_MU_GuerillaGarment2_redcamo_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment2_skull_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment2_skull_base: B_MU_GuerillaGarment2_skull_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment2_skull_base: B_MU_GuerillaGarment2_skull_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment2_brown_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment2_brown_base: B_MU_GuerillaGarment2_brown_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment2_brown_base: B_MU_GuerillaGarment2_brown_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment2_orange_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment2_orange_base: B_MU_GuerillaGarment2_orange_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment2_orange_base: B_MU_GuerillaGarment2_orange_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment2_yellow_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment2_yellow_base: B_MU_GuerillaGarment2_yellow_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment2_yellow_base: B_MU_GuerillaGarment2_yellow_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment2_blue_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment2_blue_base: B_MU_GuerillaGarment2_blue_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment2_blue_base: B_MU_GuerillaGarment2_blue_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment2_olive_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment2_olive_base: B_MU_GuerillaGarment2_olive_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment2_olive_base: B_MU_GuerillaGarment2_olive_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment2_dirty_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment2_dirty_base: B_MU_GuerillaGarment2_dirty_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment2_dirty_base: B_MU_GuerillaGarment2_dirty_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment2_green_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment2_green_base: B_MU_GuerillaGarment2_green_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment2_green_base: B_MU_GuerillaGarment2_green_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment3_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment3_base: B_MU_GuerillaGarment3_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment3_base: B_MU_GuerillaGarment3_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment3_grey_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment3_grey_base: B_MU_GuerillaGarment3_grey_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment3_grey_base: B_MU_GuerillaGarment3_grey_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment3_redcamo_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment3_redcamo_base: B_MU_GuerillaGarment3_redcamo_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment3_redcamo_base: B_MU_GuerillaGarment3_redcamo_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment3_skull_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment3_skull_base: B_MU_GuerillaGarment3_skull_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment3_skull_base: B_MU_GuerillaGarment3_skull_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment3_brown_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment3_brown_base: B_MU_GuerillaGarment3_brown_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment3_brown_base: B_MU_GuerillaGarment3_brown_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment3_orange_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment3_orange_base: B_MU_GuerillaGarment3_orange_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment3_orange_base: B_MU_GuerillaGarment3_orange_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment3_yellow_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment3_yellow_base: B_MU_GuerillaGarment3_yellow_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment3_yellow_base: B_MU_GuerillaGarment3_yellow_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment3_blue_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment3_blue_base: B_MU_GuerillaGarment3_blue_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment3_blue_base: B_MU_GuerillaGarment3_blue_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment3_olive_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment3_olive_base: B_MU_GuerillaGarment3_olive_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment3_olive_base: B_MU_GuerillaGarment3_olive_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment3_dirty_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment3_dirty_base: B_MU_GuerillaGarment3_dirty_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment3_dirty_base: B_MU_GuerillaGarment3_dirty_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment3_green_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment3_green_base: B_MU_GuerillaGarment3_green_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment3_green_base: B_MU_GuerillaGarment3_green_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment8_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment8_base: B_MU_GuerillaGarment8_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment8_base: B_MU_GuerillaGarment8_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment8_grey_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment8_grey_base: B_MU_GuerillaGarment8_grey_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment8_grey_base: B_MU_GuerillaGarment8_grey_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment8_skull_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment8_skull_base: B_MU_GuerillaGarment8_skull_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment8_skull_base: B_MU_GuerillaGarment8_skull_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment8_brown_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment8_brown_base: B_MU_GuerillaGarment8_brown_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment8_brown_base: B_MU_GuerillaGarment8_brown_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment8_olive_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment8_olive_base: B_MU_GuerillaGarment8_olive_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment8_olive_base: B_MU_GuerillaGarment8_olive_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment8_dirty_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment8_dirty_base: B_MU_GuerillaGarment8_dirty_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment8_dirty_base: B_MU_GuerillaGarment8_dirty_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment8_green_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment8_green_base: B_MU_GuerillaGarment8_green_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment8_green_base: B_MU_GuerillaGarment8_green_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment6_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment6_base: B_MU_GuerillaGarment6_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment6_base: B_MU_GuerillaGarment6_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment6_grey_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment6_grey_base: B_MU_GuerillaGarment6_grey_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment6_grey_base: B_MU_GuerillaGarment6_grey_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment6_skull_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment6_skull_base: B_MU_GuerillaGarment6_skull_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment6_skull_base: B_MU_GuerillaGarment6_skull_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment6_brown_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment6_brown_base: B_MU_GuerillaGarment6_brown_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment6_brown_base: B_MU_GuerillaGarment6_brown_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment6_olive_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment6_olive_base: B_MU_GuerillaGarment6_olive_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment6_olive_base: B_MU_GuerillaGarment6_olive_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment6_dirty_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment6_dirty_base: B_MU_GuerillaGarment6_dirty_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment6_dirty_base: B_MU_GuerillaGarment6_dirty_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment6_green_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment6_green_base: B_MU_GuerillaGarment6_green_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment6_green_base: B_MU_GuerillaGarment6_green_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment4_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment4_base: B_MU_GuerillaGarment4_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment4_base: B_MU_GuerillaGarment4_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment4_grey_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment4_grey_base: B_MU_GuerillaGarment4_grey_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment4_grey_base: B_MU_GuerillaGarment4_grey_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment4_redcamo_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment4_redcamo_base: B_MU_GuerillaGarment4_redcamo_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment4_redcamo_base: B_MU_GuerillaGarment4_redcamo_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment4_skull_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment4_skull_base: B_MU_GuerillaGarment4_skull_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment4_skull_base: B_MU_GuerillaGarment4_skull_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment4_brown_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment4_brown_base: B_MU_GuerillaGarment4_brown_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment4_brown_base: B_MU_GuerillaGarment4_brown_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment4_orange_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment4_orange_base: B_MU_GuerillaGarment4_orange_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment4_orange_base: B_MU_GuerillaGarment4_orange_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment4_yellow_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment4_yellow_base: B_MU_GuerillaGarment4_yellow_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment4_yellow_base: B_MU_GuerillaGarment4_yellow_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment4_blue_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment4_blue_base: B_MU_GuerillaGarment4_blue_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment4_blue_base: B_MU_GuerillaGarment4_blue_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment4_olive_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment4_olive_base: B_MU_GuerillaGarment4_olive_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment4_olive_base: B_MU_GuerillaGarment4_olive_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment4_dirty_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment4_dirty_base: B_MU_GuerillaGarment4_dirty_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment4_dirty_base: B_MU_GuerillaGarment4_dirty_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment4_green_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment4_green_base: B_MU_GuerillaGarment4_green_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment4_green_base: B_MU_GuerillaGarment4_green_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment5_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment5_base: B_MU_GuerillaGarment5_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment5_base: B_MU_GuerillaGarment5_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment5_grey_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment5_grey_base: B_MU_GuerillaGarment5_grey_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment5_grey_base: B_MU_GuerillaGarment5_grey_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment5_redcamo_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment5_redcamo_base: B_MU_GuerillaGarment5_redcamo_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment5_redcamo_base: B_MU_GuerillaGarment5_redcamo_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment5_skull_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment5_skull_base: B_MU_GuerillaGarment5_skull_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment5_skull_base: B_MU_GuerillaGarment5_skull_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment5_brown_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment5_brown_base: B_MU_GuerillaGarment5_brown_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment5_brown_base: B_MU_GuerillaGarment5_brown_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment5_orange_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment5_orange_base: B_MU_GuerillaGarment5_orange_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment5_orange_base: B_MU_GuerillaGarment5_orange_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment5_yellow_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment5_yellow_base: B_MU_GuerillaGarment5_yellow_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment5_yellow_base: B_MU_GuerillaGarment5_yellow_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment5_blue_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment5_blue_base: B_MU_GuerillaGarment5_blue_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment5_blue_base: B_MU_GuerillaGarment5_blue_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment5_olive_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment5_olive_base: B_MU_GuerillaGarment5_olive_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment5_olive_base: B_MU_GuerillaGarment5_olive_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment5_dirty_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment5_dirty_base: B_MU_GuerillaGarment5_dirty_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment5_dirty_base: B_MU_GuerillaGarment5_dirty_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment5_green_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment5_green_base: B_MU_GuerillaGarment5_green_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment5_green_base: B_MU_GuerillaGarment5_green_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment7_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment7_base: B_MU_GuerillaGarment7_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment7_base: B_MU_GuerillaGarment7_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment7_grey_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment7_grey_base: B_MU_GuerillaGarment7_grey_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment7_grey_base: B_MU_GuerillaGarment7_grey_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment7_redcamo_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment7_redcamo_base: B_MU_GuerillaGarment7_redcamo_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment7_redcamo_base: B_MU_GuerillaGarment7_redcamo_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment7_skull_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment7_skull_base: B_MU_GuerillaGarment7_skull_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment7_skull_base: B_MU_GuerillaGarment7_skull_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment7_brown_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment7_brown_base: B_MU_GuerillaGarment7_brown_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment7_brown_base: B_MU_GuerillaGarment7_brown_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment7_orange_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment7_orange_base: B_MU_GuerillaGarment7_orange_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment7_orange_base: B_MU_GuerillaGarment7_orange_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment7_yellow_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment7_yellow_base: B_MU_GuerillaGarment7_yellow_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment7_yellow_base: B_MU_GuerillaGarment7_yellow_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment7_blue_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment7_blue_base: B_MU_GuerillaGarment7_blue_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment7_blue_base: B_MU_GuerillaGarment7_blue_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment7_olive_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment7_olive_base: B_MU_GuerillaGarment7_olive_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment7_olive_base: B_MU_GuerillaGarment7_olive_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment7_dirty_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment7_dirty_base: B_MU_GuerillaGarment7_dirty_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment7_dirty_base: B_MU_GuerillaGarment7_dirty_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment7_green_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment7_green_base: B_MU_GuerillaGarment7_green_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment7_green_base: B_MU_GuerillaGarment7_green_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment_tank_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment_tank_base: B_MU_GuerillaGarment_tank_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment_tank_base: B_MU_GuerillaGarment_tank_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment2_tank_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment2_tank_base: B_MU_GuerillaGarment2_tank_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment2_tank_base: B_MU_GuerillaGarment2_tank_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment3_tank_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment3_tank_base: B_MU_GuerillaGarment3_tank_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment3_tank_base: B_MU_GuerillaGarment3_tank_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment6_tank_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment6_tank_base: B_MU_GuerillaGarment6_tank_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment6_tank_base: B_MU_GuerillaGarment6_tank_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment8_tank_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment8_tank_base: B_MU_GuerillaGarment8_tank_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment8_tank_base: B_MU_GuerillaGarment8_tank_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment_tank_g_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment_tank_g_base: B_MU_GuerillaGarment_tank_g_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment_tank_g_base: B_MU_GuerillaGarment_tank_g_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment2_tank_g_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment2_tank_g_base: B_MU_GuerillaGarment2_tank_g_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment2_tank_g_base: B_MU_GuerillaGarment2_tank_g_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment3_tank_g_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment3_tank_g_base: B_MU_GuerillaGarment3_tank_g_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment3_tank_g_base: B_MU_GuerillaGarment3_tank_g_base { scope = 1; scopeCurator = 1; };
class B_MU_GuerillaGarment6_tank_g_base: B_G_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_GuerillaGarment6_tank_g_base: B_MU_GuerillaGarment6_tank_g_base { scope = 1; scopeCurator = 1; };
class I_MU_GuerillaGarment6_tank_g_base: B_MU_GuerillaGarment6_tank_g_base { scope = 1; scopeCurator = 1; };
class MU_NATO_T_Strider: MU_NATO_Strider { scope = 1; scopeCurator = 1; };
class MU_NATO_T_Strider_HMG: MU_NATO_Strider_HMG { scope = 1; scopeCurator = 1; };
class MU_NATO_T_Strider_GMG: MU_NATO_Strider_GMG { scope = 1; scopeCurator = 1; };
class MU_NATO_T_Panther_unarmed: MU_NATO_Panther_unarmed { scope = 1; scopeCurator = 1; };
class MU_CSAT_T_Marid_unarmed: MU_CSAT_Marid_unarmed { scope = 1; scopeCurator = 1; };
class O_MU_islam_base_F: O_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_islam_R1_F: O_MU_islam_base_F { scope = 1; scopeCurator = 1; };
class O_MU_islam_SL_F: O_MU_islam_base_F { scope = 1; scopeCurator = 1; };
class O_MU_islam_TL_F: O_MU_islam_base_F { scope = 1; scopeCurator = 1; };
class O_MU_islam_GL_F: O_MU_islam_base_F { scope = 1; scopeCurator = 1; };
class O_MU_islam_AR_F: O_MU_islam_base_F { scope = 1; scopeCurator = 1; };
class O_MU_islam_medic_F: O_MU_islam_base_F { scope = 1; scopeCurator = 1; };
class O_MU_islam_A_F: O_MU_islam_base_F { scope = 1; scopeCurator = 1; };
class O_MU_islam_AT_F: O_MU_islam_base_F { scope = 1; scopeCurator = 1; };
class O_MU_islam_HAT: O_MU_islam_AT_F { scope = 1; scopeCurator = 1; };
class O_MU_islam_AA_F: O_MU_islam_base_F { scope = 1; scopeCurator = 1; };
class O_MU_islam_engineer_F: O_MU_islam_base_F { scope = 1; scopeCurator = 1; };
class O_MU_islam_R2_F: O_MU_islam_base_F { scope = 1; scopeCurator = 1; };
class O_MU_islam_R3_F: O_MU_islam_base_F { scope = 1; scopeCurator = 1; };
class O_MU_islam_M_F: O_MU_islam_base_F { scope = 1; scopeCurator = 1; };
class O_MU_islam_Offroad_01_armed_F: I_G_Offroad_01_armed_F { scope = 1; scopeCurator = 1; };
class O_MU_islam_Offroad_01_F: I_G_Offroad_01_F { scope = 1; scopeCurator = 1; };
class O_MU_islam_Offroad_01_repair_F: B_G_Offroad_01_repair_F { scope = 1; scopeCurator = 1; };
class O_MU_islam_Van_01_F: C_Van_01_transport_F { scope = 1; scopeCurator = 1; };
class O_MU_IS_Quadbike_01_F: C_Quadbike_01_F { scope = 1; scopeCurator = 1; };
class O_MU_IS_Boat_Transport_01_F: O_G_Boat_Transport_01_F { scope = 1; scopeCurator = 1; };
class O_MU_IS_Mortar_01_F: O_G_Mortar_01_F { scope = 1; scopeCurator = 1; };
class O_MU_IS_static_AT_F: O_static_AT_F { scope = 1; scopeCurator = 1; };
class O_MU_IS_HMG_02_high: O_G_HMG_02_high_F { scope = 1; scopeCurator = 1; };
class O_MU_IS_HMG_02: O_G_HMG_02_F { scope = 1; scopeCurator = 1; };
class O_MU_IS_Jeep: Offroad_02_unarmed_base_F { scope = 1; scopeCurator = 1; };
class O_MU_IS_Jeep_MG: Offroad_02_LMG_base_F { scope = 1; scopeCurator = 1; };
class O_MU_IS_Jeep_AT: Offroad_02_AT_base_F { scope = 1; scopeCurator = 1; };
class O_MU_IS_rhib: Boat_Transport_02_base_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_soldier_base: B_Soldier_base_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_soldier_r1: O_MU_LIVP_soldier_base { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_soldier_ar: O_MU_LIVP_soldier_base { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_soldier_medic: O_MU_LIVP_soldier_base { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_soldier_tl: O_MU_LIVP_soldier_base { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_soldier_m: O_MU_LIVP_soldier_base { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_soldier_r2: O_MU_LIVP_soldier_base { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_soldier_eng: O_MU_LIVP_soldier_base { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_soldier_a: O_MU_LIVP_soldier_base { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_soldier_gl: O_MU_LIVP_soldier_base { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_soldier_at: O_MU_LIVP_soldier_base { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_soldier_aa: O_MU_LIVP_soldier_base { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_offroad: O_G_Offroad_01_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_offroad_armed: I_G_Offroad_01_armed_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_offroad_AT: O_G_Offroad_01_AT_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_offroad_repair: O_G_Offroad_01_repair_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_RHIB: Boat_Transport_02_base_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_boat: O_G_Boat_Transport_01_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_jeep: I_C_Offroad_02_unarmed_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_jeep_armed: I_C_Offroad_02_LMG_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_jeep_AT: I_C_Offroad_02_AT_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_van: O_G_Van_02_vehicle_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_van_transport: O_G_Van_02_transport_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_truck: O_G_Van_01_transport_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_truck_fuel: O_G_Van_01_fuel_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_mortar: O_G_Mortar_01_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_static_AT: O_static_AT_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_HMG_02_high: O_G_HMG_02_high_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_HMG_02: O_G_HMG_02_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_quad: O_G_Quadbike_01_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_kamaz: C_Truck_02_transport_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_kamaz_covered: C_Truck_02_covered_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_kamaz_box: C_Truck_02_box_F { scope = 1; scopeCurator = 1; };
class O_MU_LIVP_kamaz_fuel: C_Truck_02_fuel_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_base_F: I_soldier_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_base_2_F: I_MU_mercs_base_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_R1_F: I_MU_mercs_base_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_TL1_F: I_MU_mercs_base_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_GL1_F: I_MU_mercs_base_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_M_F: I_MU_mercs_base_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_AR_F: I_MU_mercs_base_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_medic_F: I_MU_mercs_base_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_AT_F: I_MU_mercs_base_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_AA_F: I_MU_mercs_base_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_sniper_F: I_MU_mercs_base_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_A_F: I_MU_mercs_base_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_engineer_F: I_MU_mercs_base_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_chef_F: I_MU_mercs_base_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_helipilot_F: I_MU_mercs_base_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_R2_F: I_MU_mercs_base_2_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_R3_F: I_MU_mercs_base_2_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_R4_F: I_MU_mercs_base_2_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_TL2_F: I_MU_mercs_base_2_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_GL2_F: I_MU_mercs_base_2_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_Boat_Transport_01_F: O_G_Boat_Transport_01_F { scope = 1; scopeCurator = 1; };
class O_MU_mercs_Boat_Transport_01_F: I_MU_mercs_Boat_Transport_01_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_rhib: Boat_Transport_02_base_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_Jeep: I_C_Offroad_02_unarmed_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_Jeep_MG: I_C_Offroad_02_LMG_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_Jeep_AT: I_C_Offroad_02_AT_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_Offroad_01_F: I_G_Offroad_01_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_Offroad_01_armed_F: I_G_Offroad_01_armed_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_Offroad_01_repair_F: Offroad_01_repair_military_base_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_Offroad_01_covered: Offroad_01_military_covered_base_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_Offroad_01_comms: Offroad_01_military_comms_base_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_Quadbike_01_F: C_Quadbike_01_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_MD500: C_Heli_Light_01_civil_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_Mortar_01_F: I_G_Mortar_01_F { scope = 1; scopeCurator = 1; };
class O_MU_mercs_Mortar_01_F: I_MU_mercs_Mortar_01_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_HMG_02_high: I_G_HMG_02_high_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_HMG_02: I_G_HMG_02_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_caesar: Plane_Civil_01_base_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_SUV: C_SUV_01_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_truck: C_Van_01_transport_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_van: C_Van_02_vehicle_F { scope = 1; scopeCurator = 1; };
class I_MU_mercs_van_transport: C_Van_02_transport_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_base_F: O_Soldier_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_R_F: O_MU_militia_base_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_Officer_F: O_MU_militia_base_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_SL_F: O_MU_militia_base_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_TL_F: O_MU_militia_base_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_GL_F: O_MU_militia_base_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_crew_F: O_MU_militia_base_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_MG_F: O_MU_militia_base_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_AR_F: O_MU_militia_base_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_medic_F: O_MU_militia_base_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_A_F: O_MU_militia_base_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_M_F: O_MU_militia_base_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_AT_F: O_MU_militia_base_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_AT2: O_MU_militia_AT_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_HAT: O_MU_militia_AT_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_AA_F: O_MU_militia_base_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_engineer_F: O_MU_militia_base_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_sniper_F: O_MU_militia_base_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_RL_F: O_MU_militia_base_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_helipilot_F: O_MU_militia_base_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_MG2_F: O_MU_militia_base_F { scope = 1; scopeCurator = 1; };
class O_MU_militia_AMG2_F: O_MU_militia_base_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_APC_Wheeled_02_rcws_F: O_APC_Wheeled_02_rcws_v2_F { scope = 1; scopeCurator = 1; };
class MU_MIL_Marid_unarmed: MU_CSAT_Marid_unarmed { scope = 1; scopeCurator = 1; };
class O_MU_MIL_APC_Wheeled_03_cannon: I_APC_Wheeled_03_cannon_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_Van_02_vehicle: Van_02_vehicle_base_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_Van_02_transport: Van_02_transport_base_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_Truck_02_covered_F: O_Truck_02_covered_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_Truck_02_transport_F: O_Truck_02_transport_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_Truck_02_box_F: O_Truck_02_box_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_Truck_02_medical_F: O_Truck_02_medical_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_Truck_02_Ammo_F: O_Truck_02_Ammo_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_Truck_02_fuel_F: O_Truck_02_fuel_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_Quadbike_01_F: C_Quadbike_01_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_Boat_Transport_01_F: O_G_Boat_Transport_01_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_Mortar_01_F: O_G_Mortar_01_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_HMG_01_F: O_HMG_01_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_HMG_01_high_F: O_HMG_01_high_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_HMG_02_high: O_G_HMG_02_high_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_HMG_02: O_G_HMG_02_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_Jeep: Offroad_02_unarmed_base_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_Jeep_MG: Offroad_02_LMG_base_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_rhib: Boat_Transport_02_base_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_offroad: I_G_Offroad_01_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_offroad_covered: Offroad_01_military_covered_base_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_offroad_comms: Offroad_01_military_comms_base_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_offroad_repair: Offroad_01_repair_military_base_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_offroad_armed: I_G_Offroad_01_armed_F { scope = 1; scopeCurator = 1; };
class MU_CTRG_HummingBird: B_Heli_Light_01_F { scope = 1; scopeCurator = 1; };
class MU_CTRG_pawnee: B_Heli_Light_01_armed_F { scope = 1; scopeCurator = 1; };
class MU_NATO_Gorgon: I_APC_Wheeled_03_cannon_F { scope = 1; scopeCurator = 1; };
class MU_AAF_HummingBird: B_Heli_Light_01_F { scope = 1; scopeCurator = 1; };
class MU_AAF_pawnee: B_Heli_Light_01_armed_F { scope = 1; scopeCurator = 1; };
class MU_AAF_Orca_unarmed: O_Heli_Light_02_unarmed_F { scope = 1; scopeCurator = 1; };
class MU_AAF_Orca: O_Heli_Light_02_F { scope = 1; scopeCurator = 1; };
class MU_CIV_HummingBird_blueline: B_Heli_Light_01_F { scope = 1; scopeCurator = 1; };
class MU_CIV_HummingBird_elliptical: B_Heli_Light_01_F { scope = 1; scopeCurator = 1; };
class MU_CIV_HummingBird_furious: B_Heli_Light_01_F { scope = 1; scopeCurator = 1; };
class MU_CIV_HummingBird_graywatcher: B_Heli_Light_01_F { scope = 1; scopeCurator = 1; };
class MU_CIV_HummingBird_jeans: B_Heli_Light_01_F { scope = 1; scopeCurator = 1; };
class MU_CIV_HummingBird_shadow: B_Heli_Light_01_F { scope = 1; scopeCurator = 1; };
class MU_CIV_HummingBird_sheriff: B_Heli_Light_01_F { scope = 1; scopeCurator = 1; };
class MU_CIV_HummingBird_speedy: B_Heli_Light_01_F { scope = 1; scopeCurator = 1; };
class MU_CIV_HummingBird_sunset: B_Heli_Light_01_F { scope = 1; scopeCurator = 1; };
class MU_CIV_HummingBird_vrana: B_Heli_Light_01_F { scope = 1; scopeCurator = 1; };
class MU_CIV_HummingBird_wasp: B_Heli_Light_01_F { scope = 1; scopeCurator = 1; };
class MU_CIV_HummingBird_wave: B_Heli_Light_01_F { scope = 1; scopeCurator = 1; };
class MU_CIV_HummingBird_blue: B_Heli_Light_01_F { scope = 1; scopeCurator = 1; };
class MU_CIV_HummingBird_redviolet: B_Heli_Light_01_F { scope = 1; scopeCurator = 1; };
class MU_CIV_Mohawk: I_Heli_Transport_02_F { scope = 1; scopeCurator = 1; };
class MU_CIV_Orca: O_Heli_Light_02_unarmed_F { scope = 1; scopeCurator = 1; };
class MU_NATO_T_Gorgon: MU_NATO_Gorgon { scope = 1; scopeCurator = 1; };
class I_MU_mercs_HummingBird: B_Heli_Light_01_F { scope = 1; scopeCurator = 1; };
class MU_MERC_HummingBird: I_MU_mercs_HummingBird { scope = 1; scopeCurator = 1; };
class I_MU_mercs_Mohawk: I_Heli_Transport_02_F { scope = 1; scopeCurator = 1; };
class MU_MERC_Mohawk: I_MU_mercs_Mohawk { scope = 1; scopeCurator = 1; };
class I_MU_mercs_Orca: O_Heli_Light_02_unarmed_F { scope = 1; scopeCurator = 1; };
class O_MU_MIL_Heli_Light_02_unarmed_F: O_Heli_Light_02_unarmed_F { scope = 1; scopeCurator = 1; };
};
