// Auto-generated file. Do not edit.

class CfgVehicles {
class tacs_Van_Cargo_Base;
class B_Soldier_03_f;
class I_Heli_light_03_dynamicLoadout_F;
class B_Truck_01_transport_F;
class tacs_RHIB_Base;
class Plane_Transport_01_base_F;
class tacs_Polaris_Armed_Base;
class I_Soldier_02_F;
class I_Heli_light_03_unarmed_F;
class B_Truck_01_Repair_F;
class B_Soldier_04_f;
class B_Truck_01_fuel_F;
class tacs_Polaris_AT_Base;
class B_Heli_Light_01_F;
class B_Soldier_base_F;
class I_Soldier_base_F;
class I_Heli_Transport_02_F;
class tacs_Van_Transport_Base;
class tacs_Offroad_Base;
class tacs_Arcadian_Unarmed_Base;
class tacs_Arcadian_Armed_Base;
class tacs_Offroad_Armed_Base;
class B_Truck_01_ammo_F;
class B_RangeMaster_F;
class tacs_Polaris_Base;
class Civilian_F;
class tacs_Offroad_Covered_Base;

class tacs_HEMTT_Base: B_Truck_01_transport_F { scope = 1; scopeCurator = 1; };
class tacs_HEMTT_Repair_Base: B_Truck_01_Repair_F { scope = 1; scopeCurator = 1; };
class tacs_HEMTT_Ammo_Base: B_Truck_01_ammo_F { scope = 1; scopeCurator = 1; };
class tacs_HEMTT_Fuel_Base: B_Truck_01_fuel_F { scope = 1; scopeCurator = 1; };
class tacs_Arcadian_I_Black: tacs_Arcadian_Unarmed_Base { scope = 1; scopeCurator = 1; };
class tacs_Arcadian_I_Tan: tacs_Arcadian_Unarmed_Base { scope = 1; scopeCurator = 1; };
class tacs_Arcadian_I_Green: tacs_Arcadian_Unarmed_Base { scope = 1; scopeCurator = 1; };
class tacs_Arcadian_I_Grey: tacs_Arcadian_Unarmed_Base { scope = 1; scopeCurator = 1; };
class tacs_Arcadian_Armed_I_Black: tacs_Arcadian_Armed_Base { scope = 1; scopeCurator = 1; };
class tacs_Arcadian_Armed_I_Tan: tacs_Arcadian_Armed_Base { scope = 1; scopeCurator = 1; };
class tacs_Arcadian_Armed_I_Green: tacs_Arcadian_Armed_Base { scope = 1; scopeCurator = 1; };
class tacs_Arcadian_Armed_I_Grey: tacs_Arcadian_Armed_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Underwear_BlackLogo: B_Soldier_base_F { scope = 1; scopeCurator = 1; };
class tacs_Unit_Underwear_WhiteLogo: B_Soldier_base_F { scope = 1; scopeCurator = 1; };
class tacs_Unit_Underwear_BlueLogo: B_Soldier_base_F { scope = 1; scopeCurator = 1; };
class tacs_Unit_Underwear_GreenLogo: B_Soldier_base_F { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_Base: B_Soldier_base_F { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_ATACS_Base: tacs_Unit_Combat_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_C_Base: B_Soldier_base_F { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_Base: B_Soldier_03_f { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_ATACS_Base: tacs_Unit_Combat_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_C_Base: tacs_Unit_Combat_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_LS_Base: I_Soldier_base_F { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_RS_Base: I_Soldier_02_F { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_TP_Base: B_RangeMaster_F { scope = 1; scopeCurator = 1; };
class tacs_Unit_TShirt_Floral_Denim_Base: B_Soldier_base_F { scope = 1; scopeCurator = 1; };
class tacs_Unit_TShirt_Floral_Shorts_Base: B_Soldier_base_F { scope = 1; scopeCurator = 1; };
class tacs_Unit_HeliPilotCoveralls_Base: B_Soldier_04_f { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_BS_BP_BB: tacs_Unit_Combat_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_BS_GP_BB: tacs_Unit_Combat_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_BS_GP_TB: tacs_Unit_Combat_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_BS_TP_BB: tacs_Unit_Combat_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_BS_TP_TB: tacs_Unit_Combat_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_GS_GP_BB: tacs_Unit_Combat_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_GS_BP_BB: tacs_Unit_Combat_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_GS_TP_BB: tacs_Unit_Combat_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_BS_DGP_BB: tacs_Unit_Combat_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_TS_BP_BB: tacs_Unit_Combat_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_TS_GP_BB: tacs_Unit_Combat_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_TS_GP_TB: tacs_Unit_Combat_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_TS_TP_TB: tacs_Unit_Combat_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_WS_WP_WB: tacs_Unit_Combat_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_ATACS_ATX: tacs_Unit_Combat_LS_ATACS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_ATACS_AUX: tacs_Unit_Combat_LS_ATACS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_ATACS_IX: tacs_Unit_Combat_LS_ATACS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_ATACS_LEX: tacs_Unit_Combat_LS_ATACS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_AUSCAM: tacs_Unit_Combat_LS_ATACS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_AUSCAM_Khk: tacs_Unit_Combat_LS_ATACS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_CBPS_BP_BB: tacs_Unit_Combat_LS_C_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_CDES_TP_TB: tacs_Unit_Combat_LS_C_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_CDFS_GP_TB: tacs_Unit_Combat_LS_C_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_CLES_TP_BB: tacs_Unit_Combat_LS_C_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_CLFS_GP_BB: tacs_Unit_Combat_LS_C_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_CDBS_GP_TB: tacs_Unit_Combat_LS_C_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_CDBS_BP_BB: tacs_Unit_Combat_LS_C_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_CLBS_GP_BB: tacs_Unit_Combat_LS_C_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_CLRS_TP_BB: tacs_Unit_Combat_LS_C_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_LS_CPS_BP_BB: tacs_Unit_Combat_LS_C_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_BS_BP_BB: tacs_Unit_Combat_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_BS_GP_BB: tacs_Unit_Combat_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_BS_GP_TB: tacs_Unit_Combat_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_BS_TP_BB: tacs_Unit_Combat_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_BS_TP_TB: tacs_Unit_Combat_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_GS_GP_BB: tacs_Unit_Combat_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_GS_BP_BB: tacs_Unit_Combat_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_GS_TP_BB: tacs_Unit_Combat_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_BS_DGP_BB: tacs_Unit_Combat_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_TS_BP_BB: tacs_Unit_Combat_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_TS_GP_BB: tacs_Unit_Combat_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_TS_GP_TB: tacs_Unit_Combat_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_TS_TP_TB: tacs_Unit_Combat_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_ATACS_ATX: tacs_Unit_Combat_RS_ATACS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_ATACS_AUX: tacs_Unit_Combat_RS_ATACS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_ATACS_IX: tacs_Unit_Combat_RS_ATACS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_ATACS_LEX: tacs_Unit_Combat_RS_ATACS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_AUSCAM: tacs_Unit_Combat_RS_ATACS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_AUSCAM_Khk: tacs_Unit_Combat_RS_ATACS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_CBPS_BP_BB: tacs_Unit_Combat_RS_C_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_CDES_TP_TB: tacs_Unit_Combat_RS_C_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_CDFS_GP_TB: tacs_Unit_Combat_RS_C_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_CLES_TP_BB: tacs_Unit_Combat_RS_C_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_CLFS_GP_BB: tacs_Unit_Combat_RS_C_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_CDBS_GP_TB: tacs_Unit_Combat_RS_C_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_CDBS_BP_BB: tacs_Unit_Combat_RS_C_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_CLBS_GP_BB: tacs_Unit_Combat_RS_C_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_CLRS_TP_BB: tacs_Unit_Combat_RS_C_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Combat_RS_CPS_BP_BB: tacs_Unit_Combat_RS_C_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Floral_JP_BS_LP_BB: tacs_Unit_TShirt_Floral_Denim_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Floral_JP_RS_LP_BB: tacs_Unit_TShirt_Floral_Denim_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Floral_JP_GS_LP_BB: tacs_Unit_TShirt_Floral_Denim_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Floral_JP_WS_LP_BB: tacs_Unit_TShirt_Floral_Denim_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Floral_JP_BYS_LP_BB: tacs_Unit_TShirt_Floral_Denim_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Floral_SP_BS_LP_BB: tacs_Unit_TShirt_Floral_Shorts_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Floral_SP_RS_LP_BB: tacs_Unit_TShirt_Floral_Shorts_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Floral_SP_GS_LP_BB: tacs_Unit_TShirt_Floral_Shorts_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Floral_SP_WS_LP_BB: tacs_Unit_TShirt_Floral_Shorts_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Floral_SP_BYS_LP_BB: tacs_Unit_TShirt_Floral_Shorts_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_LS_BS_BP_BB: tacs_Unit_Garment_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_LS_BS_GP_BB: tacs_Unit_Garment_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_LS_OS_EP_TB: tacs_Unit_Garment_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_LS_GS_GP_BB: tacs_Unit_Garment_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_LS_GS_BP_BB: tacs_Unit_Garment_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_LS_GS_EP_TB: tacs_Unit_Garment_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_LS_ES_EP_TB: tacs_Unit_Garment_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_LS_ES_BP_BB: tacs_Unit_Garment_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_LS_ES_GP_BB: tacs_Unit_Garment_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_LS_TS_TP_TB: tacs_Unit_Garment_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_LS_GS_TP_TB: tacs_Unit_Garment_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_LS_TS_GP_BB: tacs_Unit_Garment_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_LS_OS_TP_TB: tacs_Unit_Garment_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_LS_TS_BP_BB: tacs_Unit_Garment_LS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_RS_BS_BP_BB: tacs_Unit_Garment_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_RS_BS_GP_BB: tacs_Unit_Garment_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_RS_OS_EP_TB: tacs_Unit_Garment_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_RS_GS_GP_BB: tacs_Unit_Garment_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_RS_GS_BP_BB: tacs_Unit_Garment_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_RS_GS_EP_TB: tacs_Unit_Garment_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_RS_ES_EP_TB: tacs_Unit_Garment_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_RS_ES_BP_BB: tacs_Unit_Garment_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_RS_ES_GP_BB: tacs_Unit_Garment_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_RS_TS_TP_TB: tacs_Unit_Garment_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_RS_GS_TP_TB: tacs_Unit_Garment_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_RS_TS_GP_BB: tacs_Unit_Garment_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_RS_OS_TP_TB: tacs_Unit_Garment_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Garment_RS_TS_BP_BB: tacs_Unit_Garment_RS_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_HeliPilotCoveralls_Black: tacs_Unit_HeliPilotCoveralls_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_HeliPilotCoveralls_Green: tacs_Unit_HeliPilotCoveralls_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_HeliPilotCoveralls_Grey: tacs_Unit_HeliPilotCoveralls_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_HeliPilotCoveralls_Sand: tacs_Unit_HeliPilotCoveralls_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Plaid_JP_GY_BP_BB: tacs_Unit_TShirt_Floral_Denim_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Plaid_JP_LP_BP_BB: tacs_Unit_TShirt_Floral_Denim_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Plaid_BP_LPP_BP_BB: tacs_Unit_TShirt_Floral_Denim_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Plaid_BP_LY_BP_BB: tacs_Unit_TShirt_Floral_Denim_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Plaid_JP_CB_BP_BB: tacs_Unit_TShirt_Floral_Denim_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Plaid_JP_RO_BP_BB: tacs_Unit_TShirt_Floral_Denim_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Plaid_JP_RT_BP_BB: tacs_Unit_TShirt_Floral_Denim_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Plaid_SP_GY_BP_BB: tacs_Unit_TShirt_Floral_Shorts_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Plaid_SP_LP_BP_BB: tacs_Unit_TShirt_Floral_Shorts_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Plaid_SP_LPP_BP_BB: tacs_Unit_TShirt_Floral_Shorts_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Plaid_SP_LY_BP_BB: tacs_Unit_TShirt_Floral_Shorts_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Plaid_SP_CB_BP_BB: tacs_Unit_TShirt_Floral_Shorts_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Plaid_SP_RO_BP_BB: tacs_Unit_TShirt_Floral_Shorts_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Plaid_SP_RT_BP_BB: tacs_Unit_TShirt_Floral_Shorts_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_CP_LS_TP_OB: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_CP_RS_LP_BB: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_CP_BS_TP_BB: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_CP_BS_TP_BB_NoLogo: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_TP_LS_TP_TB: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_TP_LS_TP_TB_NoLogo: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_TP_TS_GP_BB: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_TP_TS_GP_BB_NoLogo: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_TP_BS_TP_TB: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_TP_BS_TP_TB_NoLogo: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_TP_BS_LP_BB: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_TP_BS_LP_BB_NoLogo: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_TP_LS_GP_BB: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_TP_LS_GP_BB_NoLogo: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_TP_OS_TP_BB: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_TP_OS_TP_BB_NoLogo: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_TP_OS_LP_BB: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_TP_OS_LP_BB_NoLogo: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_TP_GS_TP_TB: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_TP_GS_TP_TB_NoLogo: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_TP_WS_TP_TB: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_TP_WS_TP_TB_NoLogo: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_WS_LP_BB: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_WS_LP_BB_NoLogo: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_TP_WS_GP_BB: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_Polo_TP_WS_GP_BB_NoLogo: tacs_Unit_Polo_TP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_TShirt_JP_Base: B_Soldier_base_F { scope = 1; scopeCurator = 1; };
class tacs_Unit_TShirt_JP_GS_LP_BB: tacs_Unit_TShirt_JP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_TShirt_JP_GS_TP_BB: tacs_Unit_TShirt_JP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_TShirt_JP_BS_LP_BB: tacs_Unit_TShirt_JP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_TShirt_JP_BS_TP_BB: tacs_Unit_TShirt_JP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_TShirt_JP_LS_LP_BB: tacs_Unit_TShirt_JP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_TShirt_JP_WS_LP_BB: tacs_Unit_TShirt_JP_Base { scope = 1; scopeCurator = 1; };
class tacs_Unit_I_Bodyguard: tacs_Unit_Polo_TP_BS_TP_TB { scope = 1; scopeCurator = 1; };
class tacs_Unit_I_Contractor: tacs_Unit_Combat_LS_BS_TP_TB { scope = 1; scopeCurator = 1; };
class tacs_Unit_I_Contractor_GL: tacs_Unit_Combat_LS_BS_TP_TB { scope = 1; scopeCurator = 1; };
class tacs_Unit_I_Engineer: tacs_Unit_Combat_RS_GS_BP_BB { scope = 1; scopeCurator = 1; };
class tacs_Unit_I_Medic: tacs_Unit_Combat_RS_BS_GP_BB { scope = 1; scopeCurator = 1; };
class tacs_Unit_I_Specialist: tacs_Unit_Combat_RS_GS_BP_BB { scope = 1; scopeCurator = 1; };
class tacs_Unit_I_TeamLeader: tacs_Unit_Combat_RS_BS_TP_BB { scope = 1; scopeCurator = 1; };
class tacs_Unit_I_Marksman: tacs_Unit_Garment_RS_GS_GP_BB { scope = 1; scopeCurator = 1; };
class tacs_Unit_I_PilotHeli: tacs_Unit_Combat_RS_BS_GP_BB { scope = 1; scopeCurator = 1; };
class tacs_Unit_I_VIP: Civilian_F { scope = 1; scopeCurator = 1; };
class tacs_C130J_Aegis_I_Theseus: Plane_Transport_01_base_F { scope = 1; scopeCurator = 1; };
class tacs_HEMTT_I_Transport: tacs_HEMTT_Base { scope = 1; scopeCurator = 1; };
class tacs_HEMTT_I_Repair: tacs_HEMTT_Repair_Base { scope = 1; scopeCurator = 1; };
class tacs_HEMTT_I_Ammo: tacs_HEMTT_Ammo_Base { scope = 1; scopeCurator = 1; };
class tacs_HEMTT_I_Fuel: tacs_HEMTT_Fuel_Base { scope = 1; scopeCurator = 1; };
class tacs_Offroad_I_Black: tacs_Offroad_Base { scope = 1; scopeCurator = 1; };
class tacs_Offroad_I_Covered_Black: tacs_Offroad_Covered_Base { scope = 1; scopeCurator = 1; };
class tacs_Offroad_I_Armed_Black: tacs_Offroad_Armed_Base { scope = 1; scopeCurator = 1; };
class tacs_Polaris_I_Black: tacs_Polaris_Base { scope = 1; scopeCurator = 1; };
class tacs_Polaris_I_Tan: tacs_Polaris_I_Black { scope = 1; scopeCurator = 1; };
class tacs_Polaris_I_Green: tacs_Polaris_I_Black { scope = 1; scopeCurator = 1; };
class tacs_Polaris_I_Armed_Black: tacs_Polaris_Armed_Base { scope = 1; scopeCurator = 1; };
class tacs_Polaris_I_Armed_Tan: tacs_Polaris_I_Armed_Black { scope = 1; scopeCurator = 1; };
class tacs_Polaris_I_Armed_Green: tacs_Polaris_I_Armed_Black { scope = 1; scopeCurator = 1; };
class tacs_Polaris_I_AT_Black: tacs_Polaris_AT_Base { scope = 1; scopeCurator = 1; };
class tacs_Polaris_I_AT_Tan: tacs_Polaris_I_AT_Black { scope = 1; scopeCurator = 1; };
class tacs_Polaris_I_AT_Green: tacs_Polaris_I_AT_Black { scope = 1; scopeCurator = 1; };
class tacs_RHIB_I_Theseus_Black: tacs_RHIB_Base { scope = 1; scopeCurator = 1; };
class tacs_Van_Cargo_I_Black: tacs_Van_Cargo_Base { scope = 1; scopeCurator = 1; };
class tacs_Van_Transport_I_Black: tacs_Van_Transport_Base { scope = 1; scopeCurator = 1; };
class tacs_Arcadian_B_Black: tacs_Arcadian_I_Black { scope = 1; scopeCurator = 1; };
class tacs_Arcadian_B_Tan: tacs_Arcadian_I_Tan { scope = 1; scopeCurator = 1; };
class tacs_Arcadian_B_Green: tacs_Arcadian_I_Green { scope = 1; scopeCurator = 1; };
class tacs_Arcadian_B_Grey: tacs_Arcadian_I_Grey { scope = 1; scopeCurator = 1; };
class tacs_Arcadian_Armed_B_Black: tacs_Arcadian_Armed_I_Black { scope = 1; scopeCurator = 1; };
class tacs_Arcadian_Armed_B_Tan: tacs_Arcadian_Armed_I_Tan { scope = 1; scopeCurator = 1; };
class tacs_Arcadian_Armed_B_Green: tacs_Arcadian_Armed_I_Green { scope = 1; scopeCurator = 1; };
class tacs_Arcadian_Armed_B_Grey: tacs_Arcadian_Armed_I_Grey { scope = 1; scopeCurator = 1; };
class tacs_Unit_B_Bodyguard: tacs_Unit_I_Bodyguard { scope = 1; scopeCurator = 1; };
class tacs_Unit_B_Contractor: tacs_Unit_I_Contractor { scope = 1; scopeCurator = 1; };
class tacs_Unit_B_Contractor_GL: tacs_Unit_I_Contractor_GL { scope = 1; scopeCurator = 1; };
class tacs_Unit_B_Engineer: tacs_Unit_I_Engineer { scope = 1; scopeCurator = 1; };
class tacs_Unit_B_Medic: tacs_Unit_I_Medic { scope = 1; scopeCurator = 1; };
class tacs_Unit_B_Specialist: tacs_Unit_I_Specialist { scope = 1; scopeCurator = 1; };
class tacs_Unit_B_TeamLeader: tacs_Unit_I_TeamLeader { scope = 1; scopeCurator = 1; };
class tacs_Unit_B_Marksman: tacs_Unit_I_Marksman { scope = 1; scopeCurator = 1; };
class tacs_Unit_B_PilotHeli: tacs_Unit_I_PilotHeli { scope = 1; scopeCurator = 1; };
class tacs_Unit_B_VIP: tacs_Unit_I_VIP { scope = 1; scopeCurator = 1; };
class tacs_C130J_Aegis_B_Theseus: tacs_C130J_Aegis_I_Theseus { scope = 1; scopeCurator = 1; };
class tacs_HEMTT_B_Transport: tacs_HEMTT_I_Transport { scope = 1; scopeCurator = 1; };
class tacs_HEMTT_B_Repair: tacs_HEMTT_I_Repair { scope = 1; scopeCurator = 1; };
class tacs_HEMTT_B_Ammo: tacs_HEMTT_I_Ammo { scope = 1; scopeCurator = 1; };
class tacs_HEMTT_B_Fuel: tacs_HEMTT_I_Fuel { scope = 1; scopeCurator = 1; };
class tacs_Offroad_B_Black: tacs_Offroad_I_Black { scope = 1; scopeCurator = 1; };
class tacs_Offroad_B_Covered_Black: tacs_Offroad_I_Covered_Black { scope = 1; scopeCurator = 1; };
class tacs_Offroad_B_Armed_Black: tacs_Offroad_I_Armed_Black { scope = 1; scopeCurator = 1; };
class tacs_Polaris_B_Black: tacs_Polaris_I_Black { scope = 1; scopeCurator = 1; };
class tacs_Polaris_B_Tan: tacs_Polaris_I_Tan { scope = 1; scopeCurator = 1; };
class tacs_Polaris_B_Green: tacs_Polaris_I_Green { scope = 1; scopeCurator = 1; };
class tacs_Polaris_B_Armed_Black: tacs_Polaris_I_Armed_Black { scope = 1; scopeCurator = 1; };
class tacs_Polaris_B_Armed_Tan: tacs_Polaris_I_Armed_Tan { scope = 1; scopeCurator = 1; };
class tacs_Polaris_B_Armed_Green: tacs_Polaris_I_Armed_Green { scope = 1; scopeCurator = 1; };
class tacs_Polaris_B_AT_Black: tacs_Polaris_I_AT_Black { scope = 1; scopeCurator = 1; };
class tacs_Polaris_B_AT_Tan: tacs_Polaris_I_AT_Tan { scope = 1; scopeCurator = 1; };
class tacs_Polaris_B_AT_Green: tacs_Polaris_I_AT_Green { scope = 1; scopeCurator = 1; };
class tacs_RHIB_B_Theseus_Black: tacs_RHIB_I_Theseus_Black { scope = 1; scopeCurator = 1; };
class tacs_Van_Cargo_B_Black: tacs_Van_Cargo_I_Black { scope = 1; scopeCurator = 1; };
class tacs_Van_Transport_B_Black: tacs_Van_Transport_I_Black { scope = 1; scopeCurator = 1; };
class tacs_Merlin_Base: I_Heli_Transport_02_F { scope = 1; scopeCurator = 1; };
class tacs_Heli_Wildcat_Base: I_Heli_light_03_dynamicLoadout_F { scope = 1; scopeCurator = 1; };
class tacs_Heli_I_Wildcat_Unarmed_Base: I_Heli_light_03_unarmed_F { scope = 1; scopeCurator = 1; };
class tacs_Heli_I_Merlin_Theseus: tacs_Merlin_Base { scope = 1; scopeCurator = 1; };
class tacs_Heli_I_MH6_Blue: B_Heli_Light_01_F { scope = 1; scopeCurator = 1; };
class tacs_Heli_I_Wildcat_Theseus: tacs_Heli_Wildcat_Base { scope = 1; scopeCurator = 1; };
class tacs_Heli_I_Wildcat_Theseus_Unarmed: tacs_Heli_I_Wildcat_Unarmed_Base { scope = 1; scopeCurator = 1; };
class tacs_Heli_B_Merlin_Theseus: tacs_Heli_I_Merlin_Theseus { scope = 1; scopeCurator = 1; };
class tacs_Heli_B_MH6_Blue: tacs_Heli_I_MH6_Blue { scope = 1; scopeCurator = 1; };
class tacs_Heli_B_Wildcat_Theseus: tacs_Heli_I_Wildcat_Theseus { scope = 1; scopeCurator = 1; };
class tacs_Heli_B_Wildcat_Theseus_Unarmed: tacs_Heli_I_Wildcat_Theseus_Unarmed { scope = 1; scopeCurator = 1; };
};
