// Auto-generated file. Do not edit.

class CfgVehicles {
class AA_01_base_F;
class APC_Tracked_03_base_F;
class AT_01_base_F;
class B_APC_Wheeled_01_cannon_F;
class B_MBT_01_arty_F;
class B_MBT_01_mlrs_F;
class B_MRAP_01_F;
class B_Soldier_base_F;
class GMG_01_base_F;
class GMG_01_high_base_F;
class Heli_Light_02_unarmed_base_F;
class Heli_Transport_03_unarmed_base_F;
class I_LT_01_AA_F;
class I_Soldier_base_F;
class LSV_01_unarmed_base_F;
class LSV_02_unarmed_base_F;
class MBT_02_base_F;
class Mortar_01_base_F;
class O_Soldier_base_F;
class Offroad_01_AT_base_F;
class Offroad_01_armed_base_F;
class Offroad_01_civil_base_F;
class Offroad_01_military_covered_base_F;
class Offroad_01_repair_base_F;
class Quadbike_01_base_F;
class Truck_02_Ammo_base_F;
class Truck_02_MRL_base_F;
class Truck_02_base_F;
class Truck_02_box_base_F;
class Truck_02_fuel_base_F;
class Van_01_box_base_F;
class Van_01_fuel_base_F;
class Van_01_transport_base_F;
class Van_02_transport_base_F;
class Van_02_vehicle_base_F;
class vtf_kf_HMG_02_base_F;
class vtf_kf_HMG_02_high_base_F;

class vtf_kf_B_Soldier_Base_F: B_Soldier_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Sweater_F: vtf_kf_B_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Deserter_F: vtf_kf_B_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Rifleman_F: vtf_kf_B_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_SquadLeader_F: vtf_kf_B_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Grenadier_F: vtf_kf_B_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Rifleman_AT_F: vtf_kf_B_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Marksman_F: vtf_kf_B_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Medic_F: vtf_kf_B_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Engineer_F: vtf_kf_B_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Autorifleman_F: vtf_kf_B_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Crewman_F: vtf_kf_B_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Helipilot_F: vtf_kf_B_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Rifleman_AA_F: vtf_kf_B_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Rifleman_HAT_F: vtf_kf_B_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_recon_TL_F: vtf_kf_B_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_recon_medic_F: vtf_kf_B_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_recon_M_F: vtf_kf_B_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_recon_E_F: vtf_kf_B_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Offroad_01_covered_F: Offroad_01_military_covered_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Van_02_vehicle_F: Van_02_vehicle_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Van_02_transport_F: Van_02_transport_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Truck_02_F: Truck_02_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Truck_02_Box_F: Truck_02_box_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Truck_02_Fuel_F: Truck_02_fuel_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Truck_02_Ammo_F: Truck_02_Ammo_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_APC_tracked_03_base_F: APC_Tracked_03_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_APC_tracked_03_cannon_F: vtf_kf_B_APC_tracked_03_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_APC_Wheeled_01_cannon_F: B_APC_Wheeled_01_cannon_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_MRAP_01_F: B_MRAP_01_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_LSV_01_unarmed_F: LSV_01_unarmed_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_MBT_02_base_F: MBT_02_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_MBT_02_cannon_F: vtf_kf_B_MBT_02_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_MBT_01_mlrs_F: B_MBT_01_mlrs_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_MBT_01_arty_F: B_MBT_01_arty_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_LT_01_AA_F: I_LT_01_AA_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Mortar_01_F: Mortar_01_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Heli_Transport_03_unarmed_F: Heli_Transport_03_unarmed_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Truck_02_MRL_F: Truck_02_MRL_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_GMG_01_F: GMG_01_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_GMG_01_high_F: GMG_01_high_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_static_AA_F: AA_01_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_static_AT_F: AT_01_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_HMG_02_F: vtf_kf_HMG_02_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_HMG_02_high_F: vtf_kf_HMG_02_high_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Quadbike_01_F: Quadbike_01_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_FL_Soldier_Base_F: B_Soldier_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Looter_F: vtf_kf_B_FL_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_FL_Rifleman_F: vtf_kf_B_FL_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_FL_SquadLeader_F: vtf_kf_B_FL_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_FL_Grenadier_F: vtf_kf_B_FL_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_FL_Rifleman_AT_F: vtf_kf_B_FL_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_FL_Marksman_F: vtf_kf_B_FL_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_FL_Medic_F: vtf_kf_B_FL_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_FL_Engineer_F: vtf_kf_B_FL_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_FL_Autorifleman_F: vtf_kf_B_FL_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_FL_Offroad_01_covered_F: Offroad_01_military_covered_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_FL_Quadbike_01_F: Quadbike_01_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_Soldier_Base_F: O_Soldier_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_Rifleman_F: vtf_kf_O_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_SquadLeader_F: vtf_kf_O_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_Grenadier_F: vtf_kf_O_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_Rifleman_AT_F: vtf_kf_O_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_Marksman_F: vtf_kf_O_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_Medic_F: vtf_kf_O_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_Engineer_F: vtf_kf_O_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_Autorifleman_F: vtf_kf_O_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_Crewman_F: vtf_kf_O_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_Helipilot_F: vtf_kf_O_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_Rifleman_AA_F: vtf_kf_O_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_Rifleman_HAT_F: vtf_kf_O_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_recon_TL_F: vtf_kf_O_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_recon_medic_F: vtf_kf_O_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_recon_M_F: vtf_kf_O_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_recon_E_F: vtf_kf_O_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_Offroad_01_covered_F: Offroad_01_military_covered_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_LSV_02_unarmed_F: LSV_02_unarmed_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_Van_02_transport_F: Van_02_transport_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Van_01_transport_F: Van_01_transport_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Van_01_box_F: Van_01_box_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_B_Van_01_fuel_F: Van_01_fuel_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_MBT_02_base_F: MBT_02_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_MBT_02_cannon_F: vtf_kf_O_MBT_02_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_Mortar_01_F: Mortar_01_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_Offroad_01_HMG_F: Offroad_01_armed_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_Offroad_01_AT_F: Offroad_01_AT_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_Heli_Light_02_unarmed_F: Heli_Light_02_unarmed_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_Truck_02_MRL_F: Truck_02_MRL_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_Offroad_01_repair_F: Offroad_01_repair_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_GMG_01_F: GMG_01_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_GMG_01_high_F: GMG_01_high_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_static_AA_F: AA_01_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_static_AT_F: AT_01_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_HMG_02_F: vtf_kf_HMG_02_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_HMG_02_high_F: vtf_kf_HMG_02_high_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_O_Quadbike_01_F: Quadbike_01_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_I_Soldier_Base_F: I_Soldier_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_I_Farmer_F: vtf_kf_I_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_I_Casual_F: vtf_kf_I_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_I_Leader_AKM_F: vtf_kf_I_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_I_Leader_AKS_F: vtf_kf_I_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_I_Rifleman_AKS_F: vtf_kf_I_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_I_Rifleman_AKM_F: vtf_kf_I_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_I_Marksman_F: vtf_kf_I_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_I_Rifleman_Mk14_F: vtf_kf_I_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_I_Rifleman_SG_F: vtf_kf_I_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_I_Rifleman_SO_F: vtf_kf_I_Soldier_Base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_I_Offroad_01_F: Offroad_01_civil_base_F { scope = 1; scopeCurator = 1; };
class vtf_kf_I_Quadbike_01_F: Quadbike_01_base_F { scope = 1; scopeCurator = 1; };
};
